### ISSUE TITLE
Glsl Shader support

### ISSUE THREAD

**Issue by wingedonezero** [TASVideos/desmume#103]
Can you add glsl shader support libretro has so many shaders for that format and they are compatible with most every emulator that supports them. Also they would be less performance intensive than the magnification shaders included.

**Comment by zeromus** [comment]
Which OS do you want it for

**Comment by wingedonezero** [comment]
WIndows would work i would say linux to but that might be more work.

**Comment by rogerman** [comment]
If you want GLSL shader support right now, you can use GLSL shader-based filters in the Mac version of DeSmuME. The current stable release, v0.9.11, has all of the common filters that you will need for interpolating the pixels in both older and modern ways. You can also try out a nightly build on our official Downloads page, which includes newer 5xBRZ and 6xBRZ filters that aren't present in v0.9.11. In addition, every filter available on the Mac nightly version also includes an Apple Metal equivalent shader that will be used if you are running DeSmuME on a newer Mac. Of course, running filters via GLSL/Metal is optional, and can be controlled by checking/unchecking "Run Filters on GPU".

When it comes to adding new filters, we have a different philosophy than other emulators or emulator frontends: For compatibility purposes (and for people who simply don't want to run a filter on their GPU), all filters must have a CPU-based equivalent. Filters that run on the GPU (such as GLSL or Metal shaders) are fine, but a CPU-based filter must also exist in all cases. This allows us to be able to use the same filters on all platforms. In fact, the Windows and Linux ports can already run all the filters on the CPU. However, many emulator frontends, such as RetroArch, don't maintain both CPU-based and GLSL-based equivalents for all of their filters, which disqualifies them from inclusion into DeSmuME. In addition, these same emulator frontends may have filters that work on both the CPU and the GPU using the same name and filtering paradigm, but produce different results depending on if they were run on the CPU or the GPU. For example, the GLSL-based HQnx filters used in RetroArch will produce different results than the original HQnx algorithm by Maxim Stepin. However, the GLSL-based and Metal-based filters used in Mac DeSmuME are fully compliant with the original Maxim Stepin algorithm, producing the exact same results as the original CPU-based version.

You claim that running the filters as GLSL shaders (which means running the filters on the GPU) is less performance intensive, but that is not always the case. For example, a system with a strong CPU and a weak GPU might run slower if you run the filters on the GPU. This is why this feature is optional on the Mac version, because there are many older Macs where this is exactly the case. For Windows and Linux systems, which can potentially have more varied hardware than Macs, can easily also fall under this scenario. Furthermore, both Mac and Windows ports can already run the CPU-based filters on separate threads, which hides most of the performance penalty of running the filters on the CPU. In short, I wouldn't worry too much about the performance of running filters on the CPU.

In the end, the Windows and Linux ports will not be receiving GLSL-based filters anytime soon because of the difficulty of adding new features to those frontends. The Windows frontend code must be completely reworked, while each of the Linux frontends are very fragmented. Unless new developers show up to dedicate themselves to maintaining these frontends, and until the client-layer code becomes unified for each frontend to use, don't expect these features to be added anytime soon.

Closing, since we are already fully aware of these obvious features that will be added eventually. To be fair, the unification of the client-layer code is currently in process. However, the code will not be fully unified in this coming release cycle.

**Comment by zeromus** [comment]
I doubt any user in the world has interest in the objective of feature parity between CPU and GPU filters to such a degree that they would like it to impede implementation of retroarch's GPU filters. I doubt any user in the world has any interest at all. If I could snap my fingers and make retroarch's filters happen, I would. But actually it's impossible right now, so there's no point in worrying about it.
