### ISSUE TITLE
lcd layout similar to citra

### ISSUE THREAD

**Issue by wingedonezero** [TASVideos/desmume#104]
Citra has a nice layout that if you put full screen would be great on desmume. Has a big screen for the main windows and for lower screen its smaller but still usable. I think it would work  out great.

**Comment by zeromus** [comment]
Please don't post 1000 obvious feature requests here or else I'm going to delete them all and make one ticket for wingedonezero's obvious feature requests all combined in one place

**Comment by wingedonezero** [comment]
Ok my bad i figured you would want them broken up since they were different. ill remember that next time.

**Comment by zeromus** [comment]
No, they're all the same, in that we're not going to do any of them, if it's windows or linux you want them done in.

**Comment by wingedonezero** [comment]
So what would you guys do them in then? I dont understand the last part of your comment. Do you mean its either one or the other or just not going to?

**Comment by zeromus** [comment]
Them=feature requests.

No, <feature requests> are all the same, in that we're not going to do any of <feature requests>, if it's windows or linux you want <feature requests> done in.

**Comment by wingedonezero** [comment]
Ok then figured id ask thanks for the reply.

**Comment by rogerman** [comment]
If you really need to use this feature right now, this feature is already available on the Mac version of DeSmuME. You can try it out now on a nightly build on our official Downloads page, and you will find out that the layout features you want to be superior to that of Citra. On the Mac version, NDS display layouts can be changed in the View > Display Layout menu, where the layouts you are probably looking for are "Hybrid (2:1)", "Hybrid (16:9)", and "Hybrid (16:10)", where each "hybrid" layout is specially tuned for a specific aspect ratio.

The Windows and Linux ports will not be receiving these features anytime soon because of the difficulty of adding new features to those frontends. The Windows frontend code must be completely reworked, while each of the Linux frontends are very fragmented. Unless new developers show up to dedicate themselves to maintaining these frontends, and until the client-layer code becomes unified for each frontend to use, don't expect these features to be added anytime soon.

Closing, since we are already fully aware of these obvious features that will be added eventually. To be fair, the unification of the client-layer code is currently in process. However, the code will not be fully unified in this coming release cycle.

**Comment by SigmaVirus** [comment]
@zeromus 
I'm surprised that people (including me sadly) still use DeSmuME today regarding how you treat end-users trying to get help and support, oh yeah I've read quite some disgusting comments over the years which make me want to puke.

God damn are we all scum to you or what?

@rogerman 
It's funny that you just assumed that @wingedonezero is on a Mac or even owns one to begin with.
I'm guessing he's not because otherwise he would have probably already have tried your solution out.

@wingedonezero 
If you want to use this kind of feature, RIGHT NOW then the DeSmuME Libretro core for RetroArch is what you are looking for because a similar solution is already implemented as of today.

http://buildbot.libretro.com/nightly/

![](https://cloud.githubusercontent.com/assets/22868569/19473880/47efea22-9525-11e6-8661-98adfdae514c.png)

Why RetroArch? Well it's for Windows, Linux and Mac and many other platforms.

**Comment by rogerman** [comment]
@SigmaVirus 
"It's funny that you just assumed that @wingedonezero doesn't own a Mac on the side. I'm guessing he does because otherwise he would have probably already have tried your solution out."

I realize that you needed to interpret @wingedonezero's non-response as "he doesn't own a Mac," and therefore, "you should use libretro." [clap clap] Excellent effort trying to work your obvious shilling here! One can also just as easily interpret his non-response as I had just done above. You shouldn't assume such things about the OP based purely on non-responses.

And in truth, your assumption about the OP not owning a Mac is probably the correct one. However, I was neither trying to insult fellow developers, nor make any assumptions about the OP's situation, nor be an obvious shill. I was simply trying to point out to the OP that the solution he's looking for already exists in the mainline codebase, even if it is targeted for a different platform.

Toxic responses towards @zeromus in an issues thread are not only unhelpful in resolving the issue, but also reveals your hypocrisy. If it wasn't for this, if you had just simply mentioned that there was a solution on Windows using DeSmuME for libretro, then I might have let this go. Make no mistake -- there is nothing wrong with libretro or RetroArch or the OP wanting to use those solutions, but there is everything wrong about your hypocritical attitude.

So now it's time to show why I feel absolutely zero obligation to promote any third-party frontend over mainline Mac DeSmuME at this time, and it has everything to do about existing feature sets.

Hybrid 2:1 - Balanced sizing between the major screens and the minor screens
![20171016_10-30-39 403 new mario](https://user-images.githubusercontent.com/6055122/31626084-4564685e-b25d-11e7-83ca-d65b8e5c7aaf.png)

Hybrid 16:9 - Major and minor screens sized specifically for the 16:9 aspect ratio
![20171016_10-30-41 576 new mario](https://user-images.githubusercontent.com/6055122/31626152-89f83c02-b25d-11e7-911e-c65ee945b2c3.png)

Hybrid 16:9 w/ Screen Gap - For games that account for the gap between the NDS screens, the screen gap is needed for their appearance to look correct (screen gap sizing is also available on Vertical and Hybrid 16:10 layouts)
![20171016_10-30-47 053 new mario](https://user-images.githubusercontent.com/6055122/31626231-d07ff8ae-b25d-11e7-9ac3-650fe7ff11f5.png)

Hybrid 16:10 - Major and minor screens sized specifically for the 16:10 aspect ratio
![20171016_10-30-43 468 new mario](https://user-images.githubusercontent.com/6055122/31626178-991f87d0-b25d-11e7-819c-c1b7efe92bcc.png)

Individual HD Presentation Per Screen - This isn't an actual display layout itself, but a feature that is universal to all display layouts. All screens are intelligently upscaled for best appearance. This wasn't apparent in the previous screenshots, so I took a couple more to make my point.
![20171016_10-47-16 780 new mario](https://user-images.githubusercontent.com/6055122/31626698-9a06344e-b25f-11e7-8273-b31e5cebed61.png)

![20171016_10-53-47 872 new mario](https://user-images.githubusercontent.com/6055122/31626959-6a5ab28c-b260-11e7-8081-bbd072dac8d0.png)

This is just a small taste of the display layout features present in Mac DeSmuME, in which I am only presenting the features relevant to the OP. Eventually, these same features will be coming to other platforms in the mainline DeSmuME codebase. It's something for @wingedonezero to look forward to.

**Comment by wingedonezero** [comment]
I do not have a mac so the Mac version isn't viable for me. But im glad that you did say that is in the works at some point thats all i wanted to know. I wasn't making a demand for the feature now. And as for the mention of libretro i know that option exists and i use it for psx and saturn. But im the kind of person who likes to have emulators that serve one purpose. Im not big into all in one emulators call it ocd or what ever but i think it works out better that way and easier to keep sorted.
