### ISSUE TITLE
Bug: Avalon Code: Repeatable and consistent freeze

### ISSUE THREAD

**Issue by NuclearVampire** [TASVideos/desmume#115]
Avalon Code, US Version, repeatedly freezes upon beating the forest dragon and getting the mt. elious page, at which point the top screen goes black, the music continues to play, but no matter how long you wait, or how much button pushing you try, you are stuck there.  I have not been able to get past this point, due to said freezing.   It sounds exactly like the crash mentioned [here](https://www.gamefaqs.com/boards/946197-avalon-code/51743492), but obviously they were playing on a actual ds, and had no actual information on how to deal with it. 

This is the only game I've had any sort of issue like this with.

I've tried the fixes mentioned in the faq, but don't really have any idea what else to test, but if you tell me what to do, I can follow basic instructions.

**Comment by zeromus** [comment]
If the emulator freezes in the same point as the actual game, then the emulator is working as expected.

**Comment by NuclearVampire** [comment]
The emulator doesn't freeze, only the game.  I don't know if that changes anything, but thank you for your time.

**Comment by zeromus** [comment]
Thank you for being clear and appreciating the difference. that's what I meant. If the emulator freezes, it's always  an emulator bug. Game freezing may or may not be an emulator bug--since we have documentation it happens on HW, it isn't.

However, there's one thing to be aware of.

The user on HW may have been using a flash card. Flash cards affect timing, and can make games hang. If the game never hangs on a game card (but does on a flash card) then it's a flash card bug _and_ an emulator bug. 

This is not likely to make a difference in this case. If youve changed every option affecting timing (basically everything in Emulation Settings) then there's nothing you can do and if we ever fix it, it will be on accident.
