### ISSUE TITLE
Performance is shit.

### ISSUE THREAD

**Issue by LogPod** [TASVideos/desmume#118]
Needs a major code rewrite.

**Comment by LogPod** [comment]
Kill yourself @zeromus

**Comment by fintogive** [comment]
This issue is irrelivant.  Get a new computer and stop using that old pentium 4 computer LogPod.

**Comment by LogPod** [comment]
i have an i5 6600k god damn it when upscaling to even 3 emulator slows down but it still show its running at 60fps

**Comment by LogPod** [comment]
And may i ask why there isn't a resolution selector option?

**Comment by fintogive** [comment]
Use opengl 3.2 for better speed, turn on dynamic recompiler, set frame skip to 1, use the latest build. that should help you with better performance.  im guessing you have a decent graphics card?  that will help. but overclocking your cpu will help the most.  the prescales are the resolutions.  and fyi dont tell any one to kill them selfs. you dont know who will take that seriusly.  desmume isnt like any other emulator due to how the DS works. its not GPU based.

**Comment by LogPod** [comment]
Ok thx and i'm sorry for what i said earlier

**Comment by LogPod** [comment]
I figured it out :P, all you have to do is tick filter in the display method option and fps goes to normal. no more skipping and upscaling slowdowns :)
