### ISSUE TITLE
Multisampling steps

### ISSUE THREAD

**Issue by Tatsuya79** [TASVideos/desmume#128]
It seems [DesMume is selecting the maximum of samples for anti-alisasing.](https://github.com/TASVideos/desmume/blob/master/desmume/src/OGLRender_3_2.cpp#L704)
It's quite expensive, gives me 30% dips in framerate.

Is it possible to make steps: off-2-4-8-16?

**Comment by rogerman** [comment]
You've misread the code. The actual multisample size used is limited by GetLimitedMultisampleSize(), which is just [a few lines down](https://github.com/TASVideos/desmume/blob/master/desmume/src/OGLRender_3_2.cpp#L709) from where you were.

GetLimitedMultisampleSize() will limit the multisample size depending on the framebuffer size requested. Basically, the larger the framebuffer size, the lower the multisample size becomes. In other words, multisampling steps already exist. See [OGLMaxMultisamples and OGLMaxMultisamplesScaleLimit](https://github.com/TASVideos/desmume/blob/master/desmume/src/OGLRender.h#L285) for the actual multisample steps that are being used. OpenGL's MSAA is already a hack, which is why it will always exist as a single ON-OFF option where the multisampling steps are automatic. There has been extensive testing on various GPUs to determine the best multisampling steps. However, if you want to change the steps used, you will have to build your own version of DeSmuME that has OGLMaxMultisamples and OGLMaxMultisamplesScaleLimit changed to your liking.

And finally, a 30% framerate drop is quite normal if you are using a lesser GPU with limited memory bandwidth. But with the faster GPUs (such as an Nvidia GTX 980), I've tested that you should consistently be getting a 10% FPS drop or less at all framebuffer sizes (and usually, it is less than a 5% FPS drop). If performance is that much of a concern for you, then you can always turn off MSAA, which is already a hack to begin with.

Closing, since this feature is already implemented in an automatic way, and because there is no desire to add a method for using user-defined MSAA values.
