### ISSUE TITLE
Golden Sun - Dark Dawn - Name input dialogue box disappeared in OpenGL 3.2

### ISSUE THREAD

**Issue by tabnk** [TASVideos/desmume#13]
There is an issue with OpenGL 3.2 for Golden Sun - Dark Dawn. (All default setting)

SoftRasterizer: 
![image](https://cloud.githubusercontent.com/assets/10874582/21247906/1455a8e2-c36e-11e6-8b07-a69d4e17b19c.png)

OpenGL 3.2: Disappeared
![image](https://cloud.githubusercontent.com/assets/10874582/21247988/af0b2a06-c36e-11e6-9757-21e211c55240.png)

Setting:
![image](https://cloud.githubusercontent.com/assets/10874582/21247965/86994134-c36e-11e6-8342-9340812a21ca.png)

**Comment by rogerman** [comment]
Ouch, you just stumbled on a bug involving the stencil buffer, which are bugs that are by far the most difficult of bugs to deal with in the OpenGL renderer.

This bug is a regression from r5372 when I tried to fix bugs with shadow polygons and missing polygons. Apparently, this caused the keyboard in GS:DD to disappear.

I'll have to study this issue some more. Again, this is a very difficult issue, and I'm not sure if I can maintain the same fixes from r5372 and also get the keyboard in GS:DD to reappear. Hmmmm....

**Comment by rogerman** [comment]
Fixed in commit 49309fb.

This doesn't fix shadow polygon rendering as a whole -- there are still flaws in the OpenGL renderer. But at least it allows all opaque non-shadow polygon types to render properly (such as the GS:DD keyboard). This shouldn't change the way shadow polygons are rendered right now, but this will have to be determined through additional testing.
