### ISSUE TITLE
Graphical corruption in The Legend of Zelda: Phantom Hourglass with increased resolution

### ISSUE THREAD

**Issue by windwakr** [TASVideos/desmume#132]
Bringing up the map with down on the d-pad when you have the rendering resolution set to 2x or higher results in graphical corruption while it transitions between screens. This occurs with both the softrast and OpenGL.

https://gfycat.com/WarmOblongAtlanticspadefish

![legend of zelda - phantom hourglass the__12420](https://user-images.githubusercontent.com/284886/37304519-2d3ff3dc-2608-11e8-8616-ff802c053aa0.png)

**Comment by rogerman** [comment]
Cannot reproduce. Everything seems to be working fine for me.
![20180312_12-25-12 256 zelda_ds ph](https://user-images.githubusercontent.com/6055122/37305102-9db8b6de-25f0-11e8-913b-52a6a08188b5.png)

Can you provide all the details of the particular emulation and GPU settings you are using? Or better yet, post your desmume.ini file here.

**Comment by windwakr** [comment]
This is with a fresh desmume.ini. The only change I've made is setting GPU scaling factor to 2.

**Comment by rogerman** [comment]
Oh, I see now. The map should smoothly come down from the top screen to the bottom screen, and the 3D animation should continue while the map is coming down.

It's probably a display capture bug in the GPU emulation code. I'll look at it later.

**Comment by kngrace** [comment]
I can confirm this graphical error also occurs when the game itself triggers the slide down animation such as the cutscene towards the beginning with the first treasure map. The attached photo are screen captures from two recordings I made. Left side is GPU Scaling Factor=4. Right side is GPU Scaling Factor=1. This glitch occurs for any value of GPU Scaling Factor>=2 (tested with: 2, 3, 4, 5, 6, 7, 8). 

![Zelda PH Map Slide Down Graphics Glitch](https://user-images.githubusercontent.com/5940633/54470674-4e29a100-4769-11e9-992d-0b9aa4b3fcf0.jpg)

UNRELATED: If it helps at all, the forked japanese HD version (X432R 2015.04.19) does NOT have that graphical glitch here. However, the X432R does have a graphic glitch when attempting to 'scratch off' the bottom island of this map to reveal a symbol. (see photo below of what is SUPPOSED to happen when you scratch). The X432R appears to not change transparency even when I revert back to non-HD version. I'd love to find an HD build that has _neither_ of these graphical glitches. 


![Zelda PH Map Scratch Off Transparency Example](https://user-images.githubusercontent.com/5940633/54470734-7534a280-476a-11e9-81a8-12fd40b8a5bf.jpg)

**Comment by rogerman** [comment]
So this bug has nothing to do with display capture at all. It was actually caused by an incorrect assumption that we were making.

We were assuming that the association between a particular GPU engine and a particular output display would remain constant for all 192 lines. However, this game breaks that assumption because whenever the map is moved from screen to screen, the engine/display association is changed mid-frame so that the map and the 3D stuff can draw at the desired locations on each screen.

Commit 96df034 now takes into account that games can change the engine/display association mid-frame, which includes properly maintaining all flags associated with native-sized lines and custom-sized lines.
