### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by Ken1000** [TASVideos/desmume#135]
In the DeSmuMe emulator, the buttons-'A, B, L, R, X, and Y' are not working at all.I have tried reinstalling the emulator a number of times but the problem still persists.Please help as soon as possible!

**Comment by Ken1000** [comment]
Yeah, I know that already
![capture](https://user-images.githubusercontent.com/37959742/38165865-297ec82e-3538-11e8-92cd-59a9258f02a9.PNG)


This is the picture of the controls that I set.Please help me as the problem still persists

**Comment by zeromus** [comment]
_Try a different game_

**Comment by Ken1000** [comment]
It's the same problem for all the games!

**Comment by zeromus** [comment]
Then you haven't actually tried "all the games" or you have some 3rd party junkware (most likely custom hotkey managers) breaking your system. Start uninstalling stuff.

**Comment by Ken1000** [comment]
So, is the problem with the emulator or the games?!

**Comment by zeromus** [comment]
It's confusing because your grasp of english is poor. You listed six buttons which didn't work. If there are actually twelve buttons that don't work, then you've written a confusing description of your problem.

The problem is most likely 3rd party junkware (probably custom hotkey managers) breaking your system. Start uninstalling stuff. Of course you should also try rebooting if you haven't already. 

Additionally, people frequently show up saying "no buttons work in any games!" meaning "X button doesn't work in pokemon platinum, and actually other buttons work, and I didn't actually try any different games".

**Comment by Ken1000** [comment]
Yes exactly 6 buttons didn't work and my grasp of English is fine, thank you.

**Comment by zeromus** [comment]
The problem is most likely 3rd party junkware (probably custom hotkey managers) breaking your system. Start uninstalling stuff. Of course you should also try rebooting if you haven't already. And I don't believe anyone who's said "all the games".

Also I don't see a straight column from XZSAQW on a qwerty or azerty keyboard and I don't see how it could be a straight column, since that would be too large a column for a normal keyboard.

Also, your controls are exactly the defaults, except the (Y) and (X) buttons are switched.... so.... I'm not sure you really understand what you've done?

**Comment by fintogive** [comment]
dude. just download adwcleaner.exe and jrt.exe  if you have any junkware adware or even some viruses thesewill remove them.  after that delete your desmume ini file and try again.

https://www.malwarebytes.com/adwcleaner/
https://www.malwarebytes.com/junkwareremovaltool/

**Comment by Ken1000** [comment]
I have been using it for over a year now but this is the first time I have encountered any problem.So, I am just confused.That's all!

**Comment by Ken1000** [comment]
Sorry, but the emulator isn't receiving any key presses!

**Comment by zeromus** [comment]
So this is the first time you have installed junkware or viruses.
Now it's every key and not just 6 buttons? 
Have you figured out what it means to uninstall things?
Have you uninstalled the junkware and viruses?
Have you tried the "display input" option?
Have you rebooted?
Have you deleted your desmume.ini file?
Have you listed which games you've tried, in case you're exaggerating how many games you've tested and you just don't know how to play the ones which you've tested?
Have you figured out how you bound all your controls to one column which is too tall for anyone's keyboard?
Write back when you can answer each question.

**Comment by Ken1000** [comment]
Ans.5)Yes, I have tried it.That's why I was able to tell you the answer to your 'second question'!

**Comment by Ken1000** [comment]
Ans.6)A couple of times, yes.

**Comment by Ken1000** [comment]
Ans.7)I searched for it but didn't find one on my system.

**Comment by Ken1000** [comment]
Ans.8)I have played the 'Fire Emblem, Phoenix Wright, Yu-Gi-Oh, Time Hollow, Megaman ZX Advent, etc.'

**Comment by Ken1000** [comment]
Ans.9)Just set the 6 buttons(which are not working for me) in your emulator as given in the picture above and they will sort of fall in place(like a column like- Q W
                                                                                               A S
                                                                                                Z X

**Comment by Ken1000** [comment]
I have sent all the answers you need

**Comment by zeromus** [comment]
Ans.7 is not acceptable. Learn to search your hard disk better, and find someone who knows how to use a computer if you must

You probably didn't uninstall enough junkware. Start uninstalling everything you've installed on your system, going backwards in time from today. Pay special attention to hotkey managers, streaming software, keyboard utilities or drivers, and any kind of "enhancers".

**Comment by Ken1000** [comment]
I see, OK.I will try
