### ISSUE TITLE
High CPU Usage When No Game is Loaded or Paused Emulation

### ISSUE THREAD

**Issue by wildgoosespeeder** [TASVideos/desmume#14]
I'm glad this moved on from SourceForge. GitHub is better. I was thinking about creating an account there to submit this bug report. Good thing I waited. Didn't expect this. Props for the move.

Anyways, someone on Reddit made an unofficial build where DeSmuME stopped using the CPU so heavily when no game is loaded or when the emulation is paused.

Thread:
https://www.reddit.com/r/emulation/comments/5i3yye/a_question_about_ds_local_multiplayer_emulation/db6qp48/

Build that fixes the CPU intensity when idling:
https://filebin.net/pceyvokrb4ltjqyt

The user claims that input is being checked too often and the window is being redrawn when nothing is changing.

Only regression with that is HUD display (FPS, pressed buttons, etc.) cannot be drawn on-screen regardless if enabled/disabled in the menus. I was hoping that maybe this CPU idle intensity fix could be included along with fixing the HUD code to display as well.

**Comment by zeromus** [comment]
Someone on reddit hacked GPL sources and posted a binary without sources. 

Desmume is burning CPU because of some kind of video driver **bug/feature** which is sucking down CPU in a busy loop when frames pile up. I'm 98% sure it's triggered by desmume using a thread for rendering to the screen. Are drivers assuming it's a game thread which wouldn't want to spin down under any circumstances? I dunno.

Switch to the directdraw display method and watch your cpu become 1%.

I'm interested in workarounds for buggy GPU drivers, or a patch which **adds an option** to disable the threaded display codepath (controlled currently by the single-core option which would then kill your multithreaded softrasterizer). 

If I get tired of seeing this thread put updates in my inbox, I may add that option myself. The option will be called --workaround-for-buggy-gpus-sucking-up-cpu. Or maybe --no-display-thread. I'll probably put it in the GUI near config > display method, where all the other hacks for bad GPUs are.

**Comment by wildgoosespeeder** [comment]
I am using DirectDraw. Switching to other options doesn't change anything. I'm pretty sure that the source code for the RC of 0.9.12 was used and a few lines of code were tweaked/added/removed. I don't think this is a GPU driver bug. I have used older and newer versions of the NVIDIA GeForce 610M drivers and the situation doesn't improve.

**Comment by zeromus** [comment]
It's a GPU driver bug. Some GPU drivers last for years. Some last for all of time. Trying a different driver version doesn't prove anything, nor does a dozen. I get 1% idle on my system in directdraw display method because my GPU is only half bugged (but I get one core nearly pegged in the OpenGL display method)

**Comment by rogerman** [comment]
> the source code for the RC of 0.9.12 was used
Umm... what? Do you mean "RC" as in "Release Candidate"?!!! Well that's news to me!

But in all seriousness, there isn't any Release Candidate for v0.9.12. It's still very much in development.

**Comment by wildgoosespeeder** [comment]
GPU driver bug I highly doubt. Believing that drawing to the screen when nothing is changing and the program checking an input 17 times more than required I have an easier time believing is causing the CPU usage to skyrocket.

@rogerman RC was the best term to describe source code that hasn't been compiled yet officially by the dev team.

**Comment by zeromus** [comment]
Believe what you want, but take care to square it with the observation that results differ according to system, if you can.

**Comment by tabnk** [comment]
Try the unofficial build and unexpectedly the v-sync improved a lot. Interested in what code did they change.

**Comment by zeromus** [comment]
FYI vsync doesn't even work except on the directdraw display method. I guess I added that before the opengl display method and didn't organize the menu items well. (I had to check just now).

So you probably think the vsync doesnt work well because it doesnt work at all because youre one of (using opengl display method; using a buggy driver that cant vsync ddraw properly). And for what it's worth, most drivers can't vsync ddraw now.

If youre using opengl display method, there's no effort made to vsync; except that drivers will automatically vsync forcibly oftentimes. Except they may not if they run in another thread, because who knows what drivers are thinking. So when they put the rendering in the main thread or otherwise quit tripping the driver's bugs-activation mode, it was able to act more normally and forcibly (lamely, from my point of view) force the window into vsync.

**Comment by tabnk** [comment]
I'm did used directdraw display method.  I'm compared both build 2016/12/10 – git#1787081 and the unofficial on same game by reloading save state. Perhaps some bug in Nvidia driver than.

**Comment by zeromus** [comment]
Like I said, many drivers have problems with ddraw vsync. It has to do with improved generality for multiple display devices and the like. How do you even vsync monitors running at different hz? I think at some point they quit even trying. 

It is unsurprising that something running at ~100fps looks tear-ible on a 60hz monitor (threaded HUD), compared to something clock-throttling itself to 60fps (HUD in sync with emulation)

**Comment by wildgoosespeeder** [comment]
I don't think Vsync or GPU bugs have anything to do with this intense CPU usage I am experiencing when idling. I really do think the code somewhere is just wasting CPU cycles when the emulation is inactive, achieving nothing for its efforts when those CPU cycles should be used when the emulation is active.

**Comment by zeromus** [comment]
Thanks for sharing your opinion, GPU programmer

**Comment by wildgoosespeeder** [comment]
OK, think of it this way. Why would you utilize the GPU if no ROM is loaded or if the emulation is paused? Wouldn't it make sense to turn that off when not in use?

**Comment by zeromus** [comment]
Maybe to anyone who doesn't want to see a hud animate.

**Comment by wildgoosespeeder** [comment]
Right now, HUD doesn't work. Why not investigate the code that Zapeth implemented breaks the HUD? Better yet, why not ask Zapeth directly on Reddit what he did?

**Comment by zeromus** [comment]
HUD works fine. I don't know what you're talking about. If you care so much, you ask him.

**Comment by wildgoosespeeder** [comment]
Yes, HUD works fine, in 0.9.11 and 0.9.12, your version, but Zapeth's version, it's broken when he implemented fixes to lay off the CPU when no ROM is loaded or if the emulation pauses.

**Comment by zeromus** [comment]
Zapeth broke something. It bothers you. Why are you talking to me? Talk to zapeth.

**Comment by wildgoosespeeder** [comment]
That's not what I am asking. What I am asking is if you can implement an official fix instead of zapeth's HUD-breaking fix. Personally, I don't care if HUD is broken. I rather have those elements hidden from the game.

**Comment by zeromus** [comment]
Can you read my 1st reply to your OP or am I going to need to paste it all here?

**Comment by wildgoosespeeder** [comment]
The more you talk, the more I keep thinking we aren't talking about the same thing.

**Comment by rogerman** [comment]
> That's not what I am asking. What I am asking is if you can implement an official fix instead of zapeth's HUD-breaking fix. Personally, I don't care if HUD is broken. I rather have those elements hidden from the game.

Ummm.... fixing one thing in favor of breaking another feature is really bad policy. Just because you don't use the HUD doesn't mean other people don't either. (In fact, the HUD is an extremely popular feature for most users.)

**Comment by zeromus** [comment]
I wish we weren't talking about anything at all.

**Comment by wildgoosespeeder** [comment]
@rogerman 
That's why you investigate for a fix if a code change breaks something else. I'm not asking to commit Zapeth's code changes and publish 0.9.12 with a feature that is broken. I am asking you do that but fix the introduced break as well.

**Comment by zeromus** [comment]
And I told you 3 other ways we could explore fixing the basic problem without causing the problem zapeth caused, and 1 thing you needed to do before anyone could even voice a competent opinion on what zapeth did (FIND OUT WHAT ZAPETH DID)

**Comment by zeromus** [comment]
sorry @tabnk, open a new ticket for vsync woes

**Comment by tabnk** [comment]
Ok.

**Comment by wildgoosespeeder** [comment]
@zeromus 
I think I tried to explain it to you and tell you what Zapeth did but you refused to listen.

**Comment by zeromus** [comment]
Well then you'd better find a programmer to tell it to me because I didn't hear anything that sounded like an explanation of what zapeth did.

**Comment by wildgoosespeeder** [comment]
@zeromus 
I don't need to find a programmer because if you messaged Zapeth instead of trying to 1-up me, this wouldn't have happened. I even provided the Reddit thread to make it possible!

**Comment by zeromus** [comment]
I'm not going to go to some forum to ask some guy about some buggy thing he did that I have three better solutions to when said guy has a github account (did you even check?) and you could have looped him in at any time and spent the words you spent asking me to ask him what he did asking him what he did instead.

**Comment by wildgoosespeeder** [comment]
@zeromus 
I don't know why you closed this. Issue isn't solved yet. I already linked him to the thread. I guess he isn't available yet. Let's see if he replies.

**Comment by zeromus** [comment]
I closed it because I'm tired of trying to teach you manners. It was supposed to be a sign that the thread was dead to me.  I'll let zapeth record what he did here for posterity (and to comply with the copyright law) but you've ruined this thread's usefulness for actually solving the problem. Trust me, if you want this issue fixed, it's best for you if you stop replying. All you're doing is giving me a disincentive from ever fixing it.

**Comment by zeromus** [comment]
You removed a needed 16x loop to check across 16 potential joysticks.

The only thing I can see that's nontrivial cost in that codepath is the GetForegroundWindow() in S9xGetState(). This is plausible as a performance "bug" because this would have been tacked on later after the code was ported from snes9x. As a result of this, GetForegroundWindow() is called 16*256 times when just once would be enough. That's a waste of cpu by any standards. Whether it's measurable, I dont know. 

By changing j to 16, where before it ranged from [0,15], you created bugs inside any array of length 16.

**Comment by Zapeth** [comment]
Sorry, has to be `int j = JOYSTICK?15:1` of course (though as far as I can tell it wasn't used in combination with any arrays anyway, just for flags).

**Comment by wildgoosespeeder** [comment]
@zeromus 
Now that you have some code to work with, am I right about this not even being related to a graphics driver bug as you initially thought and heavily insisted? For an Intel Core i5-3210M@2.5Ghz processor, the measurable difference in Windows Task Manager is 50% CPU usage reduction when the emulator doesn't have a ROM loaded or is paused. I don't know what processor @Zapeth is using, but if I were to guess, Intel Core i7 line and faster base speed of around 3Ghz or more. Not as extreme as I am experiencing, but is measurable.

@Zapeth 
I'm glad you came to "translate" my explanations into code.

**Comment by zeromus** [comment]
No, you're wrong. It confirms that it's a GPU driver bug, since his patch un-triggers the GPU driver bug by removing the multi-threaded codepath.

**Comment by wildgoosespeeder** [comment]
Explain the code that @Zapeth implemented that prevents the GPU driver bug.

**Comment by zeromus** [comment]
It removes the multi-threaded codepath.
@Zapeth GetKeyState() should only be happening for 1 of the iterations. Since "If it's a joystick 'key'" causes earlier code to handle those S9xGetState() invocations before the GetKeyState is called.

**Comment by wildgoosespeeder** [comment]
@zeromus 
What code though? What lines of code are you referring to that @Zapeth changed?

**Comment by zeromus** [comment]
The lines that arent about input processing
**This concludes your programming tutorial**

**Comment by wildgoosespeeder** [comment]
@zeromus 
No conclusion is reached until both parties are understanding what is going on.

Oh, you mean where @Zapeth forces a false condition to bypass those functions? CommonSettings.single_core() is that thread related to the GPU driver bug?
