### ISSUE TITLE
Firmware config doesn't save : firmware.dfc

### ISSUE THREAD

**Issue by arima0k** [TASVideos/desmume#161]
I believe, DeSmuME 0.9.12 git#6fd23368 x64-JIT SSE2, rewrits firmware.dfc after starting a Rom.
I edit and save wifi config with DNS and the WFC ID and after restarting or reopening the Rom all is gone.
I followed all [this](https://github.com/retr0s4ge/desmume/tree/master20180622_test_WiFi) instructions
(all the md5sum of the files are ok)
@retr0s4ge

**Comment by retr0s4ge** [comment]
@arima0k Works fine for me.

The behavior you describe happens if the firmware wasn't dumped correctly or wrong emulation settings were selected.

If you didn't dump the firmware files yourself, can you paste the SHA1sum or SHA256sum of the bios7.bin, bios9.bin and firmware.bin here ?

While troubleshooting, please turn off the dynamic re-compiler and avoid using save/load states.

Also, please double check that your emulation settings are exactly the same as the attached image.

![image](https://user-images.githubusercontent.com/35266374/43021318-827cb9ae-8c63-11e8-8fc1-0addc78d9723.png)

**Comment by arima0k** [comment]
I realized that the problem was in the ROM because desmume didn't detect any ds card when i booted from firmware, i downloaded another rom and it worked.
Thank you so much fot your work, i hope some day i learn to program and help.
