### ISSUE TITLE
Several features missing in GTK port

### ISSUE THREAD

**Issue by Star-X555** [TASVideos/desmume#163]
Specifically, GBA cart slot emulation, and Export Backup Data are both missing entirely from the GTK port.  There's more too, but those two are the ones I've noticed.

Some of us either don't have Windows, or don't want to use Windows, so we're kinda in a jam if we need either of those features for a game.

Incidentally, at least the latter does work if Wine is used to run the Desmume windows build, but since Desmume is open source, there is literally no reason to keep those features out of GTK.

On a similar note, the Glade port is even worse, having almost no actual functionality outside of running games, but at least GTK is offered on the same platform, seriously reducing the issue.

I do understand that the non-Windows builds are worked on by people other than the main devs, but some of these features have been missing for years after they were introduced in the Windows build, so it'd be greatly appreciated to see some effort made to unify the various options across the various ports.

**Comment by zeromus** [comment]
gba slot works via the command line. effort has been made to unify the various options across various ports. whether you've seen it is more up to you.

Please do not open tickets for "needs X on Y" or "needs several A,B,C on Y" because anyone who is going to work on those features doesn't need a list, and anyone who ever did work on those features (not likely) would probably be working on them so far in the future that any list would be out of date on account of windows features changing in the interim.
