### ISSUE TITLE
Some questions about the DESMUME project...

### ISSUE THREAD

**Issue by johnny-mac** [TASVideos/desmume#194]
Hi, I'd like to know if any of the desmume-reloaded commits have been worked into this repo or not. 
And, why has there been no release tarballs in the last while? I see the last release was back in 2015, I'd love to be able to package source tarballs directly from this repo! Thanks for your time!

**Comment by rogerman** [comment]
1. For desmume-reloaded, only the WiFi-related kinda-sorta fixes were incorporated into the master codebase. See commit 7548294 for details. (It's just the WiFi stuff from the v0.9.7 codebase, which doesn't work very well and doesn't have much practical use.) As of this date, there is no advantage to using desmume-reloaded because the current code base also has many additional changes/fixes/enhancements over desmume-reloaded. One notable enhancement is that you can completely turn WiFi off in order to save on CPU cycles.

2. The code is definitely in flux right now, which prevents us from doing a stable release at this time.

Since this ticket is just asking questions and not reporting any actual issues, I'm closing this one now. In the future, please ask your questions at forums.desmume.org instead of asking them here. The issues tracker is meant for bug reports, not for asking questions.

**Comment by johnny-mac** [comment]
Thanks for the reply Rogerman, sorry I had no idea you have a forum. I hope to contribute in the not too distant future once the code is no longer in flux. Thank you for all that you do! Have a great day!

**Comment by JackoboLeChocobo** [comment]
For desmume project ( i developped it here : https://gitlab.com/JackoboLeChocobo/Desmume-Reloaded ) , the Wifi code that I forked works as in 0.9.7 code like I already said in the forums  : the ALTWFC project has never tested the Wifi functionnality with Desmume, that's why we doesn't have the same results of their Wiki. Some games worked, and Adhoc support was not complete ( we had the Luigi doesn't see Mario issue in NSMB ) . 

I see rogerman that you have done some changes in the Wifi code : so I will test it and see if the changes that you made have much practical use than the forked code I created. I will see of course new improvements, but will they be working without modifications for Windows and Linux ? You know what I mean by that ^^ ( libpcap deps for Linux, WinPcap or other open source libpcap deps equivalent for Windows )

**Comment by rogerman** [comment]
@JackoboLeChocobo, the recent WiFi changes in master have purely been intended as code refactoring and code cleanup. Actual functional changes are just unintended consequences of the code changes. However, the time is starting to approach when I will be transitioning from simple code refactors and cleanup into attempting to improve the actual WiFi emulation. There is no hard set timeframe for this transition. The best timeframe I can describe for this is "soon."

So do the recent WiFi code changes have a "practical use"? In terms of real WiFi functionality and emulation accuracy, not really. Are there "new improvements"? There are no new improvements that are visible to the end-user. In fact, commit da714ea7 may have slightly degraded functionality in Ad-hoc mode due to the RX transfer delay change added to that mode. This is a priority issue for fixing.

Will they work without modification for Windows and Linux? Of course they will! Actually, the Linux ports now make libpcap a mandatory library for building DeSmuME, but the Windows port still doesn't require winpcap.
