### ISSUE TITLE
Allow Change of Hotkeys in Linux Version

### ISSUE THREAD

**Issue by dkl3** [TASVideos/desmume#208]
Hi, I use the Linux version of Desmume if I were to play DS games. I like to take screenshots while playing, and sometimes the right frame can be messed up if I were to quickly swap between the controller and pressing ctrl + s.

This should be an easy fix, no worries

**Comment by zeromus** [comment]
I can't make any sense out of this. Try writing it again.

**Comment by ImSpecial** [comment]
Relax dude, not everyone is a native english speaker... anyway, he probably just wants a way to rebind the screenshot hotkey to something more to his convenience because when that screenshot worthy moment happens, him having put down the control and quicky reach for the ctrl+s hotkey makes him miss said screenshot moment.

**Comment by zeromus** [comment]
#209
