### ISSUE TITLE
Who Wants to Be a Millionaire (Europe) flickering screens

### ISSUE THREAD

**Issue by benderscruffy** [TASVideos/desmume#210]
during the videos both screens flicker no matter if you choose opengl or softrasterizer and advanced bus level timing ticked or unticked

**Comment by zeromus** [comment]
Just a crappy game with bad timing. It can be fixed by decreasing the cost of DMA to vram (the screens are not swapped until the DMA is complete, so the DMA must complete before the frame begins)

Could be fixed nonintrusively with a game specific hack, but I don't feel like doing that for some intro FMVs. if the game is ruined by other broken videos in-game, I might consider it.

**Comment by benderscruffy** [comment]
https://sourceforge.net/p/desmume/bugs/703/
