### ISSUE TITLE
Request: Add Rigorous 3D Rendering Timing to Windows GUI

### ISSUE THREAD

**Issue by extherian** [TASVideos/desmume#235]
We can select "Advanced Level Bus Timing" from the GUI on Windows, but for some reason we can't do the same for "Rigorous 3D Rendering Timing". I would greatly appreciate it if someone would address this.

I am aware that it would reduce performance. I only want to have the option for comparison with melonDS, which has made GPU timing accuracy a major focus of its development.

**Comment by zeromus** [comment]
No. This is rarely required. Someone should remember what this is for and turn it into a game-specific hack.

**Comment by extherian** [comment]
The same should apply to "Advanced Level Bus Timing" as well then, shouldn't it? If these options aren't really that important, then perhaps they should both be hidden. I wonder why "Rigorous 3D Rendering Timing" was exposed on the Mac port to begin with.

By the way is it still possible to enable "Rigorous 3D Rendering Timing" by editing the INI file?

**Comment by rogerman** [comment]
I exposed Rigorous 3D Rendering Timing in the Mac port simply because it was there. Didn't you read the tooltip for the option to figure out what it does?

![cocoa_port_rigorous_3d_timing_tooltip](https://user-images.githubusercontent.com/6055122/49541842-c4745880-f888-11e8-9327-fd76cadd761a.png)

To clarify what the tooltip is saying:
All 3D rendering should be starting on line 214, which means that all 3D rendering assets also need to be completely ready by line 214. Enabling Rigorous 3D Rendering Timing emulates this correct timing.

However, internal timing issues in DeSmuME makes it so that some games don't have all of their assets (such as textures) ready by line 214, and so disabling Rigorous 3D Rendering Timing starts 3D rendering later on line 262, thereby ensuring that games are more likely to have all of their 3D assets ready by then. The reason why Rigorous 3D Rendering Timing is OFF by default is because waiting until line 262 to start rendering improves game compatibility.

As an example, Hotel Dusk: Room 215 will have many graphical glitches when this option is ON, probably because it does a bunch of internal texture changes in main RAM, but DeSmuME's flawed timing makes it so that the texture doesn't get copied to VRAM in time. And so, by turning Rigorous 3D Rendering Timing OFF, now Hotel Dusk: Room 215 has enough time to get all of its textures to VRAM and avoid the graphical glitches.

As for the performance thing: Enabling Rigorous 3D Rendering Timing allows the 3D renderer to start sooner rather than later. Since 3D rendering occurs in parallel with the 2D rendering, this gives the 3D renderer more time to work before the 2D engine needs to read the 3D layer, resulting in more stable performance.

**Comment by zeromus** [comment]
@extherian "Advanced Level Bus Timing" is too chaotic to turn into a per-game hack. at least in the case of bowser's inside story, it helps to turn it off and on at various times. It's functioning as a gross timing adjuster so you can kick things into a different profile of bugs and maybe get further through games. 

@rogerman We should rename it to "late 3d rendering hack" at least. But since you reminded me of an affected game, do you want me to go ahead and make it a per-game hack? Since it's been buried so long in the windows port and I never hear about it, there must not be many cases where controlling it is needed.

**Comment by rogerman** [comment]
@zeromus, AFAIK, Hotel Dusk is the only game that is affected by this. And in practice, I usually keep Rigorous 3D Rendering Timing ON for all the games that I test, only turning it OFF temporarily when I test Hotel Dusk. I haven't had any problems doing this... so far.

To be fair, having Rigorous 3D Rendering Timing OFF is the "safer" path, albeit at the cost of true emulation accuracy and some 3D rendering performance. I do test a lot of different games, but I definitely haven't tested the entire NDS library, so I don't know if any other games will fail like Hotel Dusk does.

I don't think enough testing has been done on this issue. So let's try this: Leave Rigorous 3D Rendering Timing as a CommonSettings option, but have it ON by default. Also make Hotel Dusk be a per-game hack that overrides the setting to OFF. No UI changes will be necessary in either the Cocoa or Windows ports. Then let the users test games for a while until someone reports a problem. Or maybe no one will report problems. Well... more testing would be a safe bet, either way.

**Comment by zeromus** [comment]
in the long run, having a cryptic provision for enabling any specific game hacks might be helpful. otherwise how do non-programmers test them? maybe we should have a --gamehacks=comma,separated,list instead.

**Comment by zeromus** [comment]
you thought wronng

**Comment by rogerman** [comment]
JIT does break Hotel Dusk if the block size is too large. Hotel Dusk will experience graphical glitches unless the JIT block size is 17 or less.

Interpreter will always be inherently more accurate than JIT because Interpreter naturally executes one instruction at a time, which helps prevent timing errors. Of course, you could always run JIT with a block size of 1 so that you can have the same timing accuracy as Interpreter, but then you would be negating the entire reason to use the JIT.

**Comment by extherian** [comment]
A block size of 15 does seem to be the cutoff point at which many games break, which makes me wonder why it's set at 12. But I'm surprised that more games don't have problems considering that the timings are so badly off. Phantom Hourglass and Spirit Tracks don't seem to be affected at all, even with the JIT block size maxed out.

So if I understand this correctly, Advanced Level Bus Timing stops some games from crashing, while Rigorous 3D Rendering Timing prevents graphical issues in most games while breaking a few others. I wanted to have both turned on for better accuracy, since the performance impact seems insignificant. But it sounds like they're both just workarounds for incorrect behaviours in DeSmuME rather than actually being more accurate.

**Comment by rogerman** [comment]
@extherian: You are correct that a block size of 15 is the cutoff point for which many games will break. However, the reason the default block size is 12 is because this is what the block size needs to be to support a full external firmware boot. Nowadays, there is an override that will temporarily force the block size to 12 if the user attempts to do a full external firmware boot, but I consider 12 to be the safest block size to use by default that should support the vast majority of games without hurting performance too much. The performance difference between 12 and 15 is negligible. Heck, the performance difference between 12 and 100 is negligible under most circumstances!

That's not to say that block size 12 is a guarantee that ALL games will work with JIT. For example, "Alice in Wonderland" requires a block size of 8 just to get past the main menu and play the game at all. I'm pretty sure that there are other games floating around out there that require a block size less than 12, but AFAIK, "Alice in Wonderland" is the only one I've found so far.

**Comment by extherian** [comment]
Now I get it...it's just impossible to have games like Hotel Dusk work correctly without hacks since modern GPUs don't render in scanlines. 

With that in mind, will we get this selectable option on Windows, or will it just be silently turned on in the background? I'd like to have the option for better accuracy on Windows as well.

I have noticed that there's no performance difference between 18-bit color and 24-bit color, but 15-bit color dramatically improves performance, especially on intensive scenes like the Spirit Tracks opening. I suppose the color depth uses up GPU bandwidth rapidly like MSAA does?

Thank you for the in-depth explanation. I believe the Dolphin team have run into the same issue, where improving accuracy in one area exposed inaccuracies in another area, ironically reducing compatibility. In Dolphin, enabling some options like Dual-Core can cause subtle bugs that the user might not notice until their save is corrupted or their game crashes, which I was hoping to avoid with DeSmuME.

**Comment by Jules-A** [comment]
> I have noticed that there's no performance difference between 18-bit color and 24-bit color, but 15-bit color dramatically improves performance, especially on intensive scenes like the Spirit Tracks opening. I suppose the color depth uses up GPU bandwidth rapidly like MSAA does?

I know this is kind of off-topic but there was a difference between 18 and 24bit on my old 5750, though still very tiny compared to 15 to 18bit. On my RX570 the difference between 15bit and 18bit is large (larger than it was on my 5750, though other settings are higher) but 18 to 24bit is practically nil. I don't think its bandwidth, seems more like it's my CPU limiting it.

**Comment by rogerman** [comment]
For @extherian:

> Now I get it...it's just impossible to have games like Hotel Dusk work correctly without hacks since modern GPUs don't render in scanlines.

That is correct -- it is impossible for games like Hotel Dusk to work correctly without hacks by virtue of using a framebuffer-based renderer rather than a scanline-based renderer.

Just know that our framebuffer-based approach provides certain features that a scanline-based approach cannot provide. Just off the top of my head, these include:
1. Faster 3D rendering performance overall.
2. The existence of the OpenGL 3D Renderer itself.
3. The future existence of any other GPU-based 3D renderers that someone may want to implement. (I am planning on making an Apple Metal renderer at some point in the future.)
4. SoftRasterizer's ability to do multithreaded clears, rasterization, and post-processing effects (such as Edge Mark and Fog).
5. The ability to perform Texture Upscaling and Texture Deposterization.
6. High-resolution 3D rendering.

Of course, all of this framebuffer-based 3D rendering stuff is legitimately inaccurate behavior. It would be nice if DeSmuME could be reworked to perform scanline-based rendering as an option. Unfortunately, implementing a scanline-based 3D renderer would also require us to rework our DMA and GXFIFO timings, which are also less than perfect. Because of all of these reasons, don't expect this to happen any time soon!

> With that in mind, will we get this selectable option on Windows, or will it just be silently turned on in the background? I'd like to have the option for better accuracy on Windows as well.

Neither.

The Rigorous 3D Rendering Timing option will not be explicitly exposed in the Windows port. However, this option will be reimplemented as a per-game hack, and so you will be able to indirectly control it through Enable Game Hacks.

> I have noticed that there's no performance difference between 18-bit color and 24-bit color, but 15-bit color dramatically improves performance, especially on intensive scenes like the Spirit Tracks opening. I suppose the color depth uses up GPU bandwidth rapidly like MSAA does?

First off, MSAA is purely a GPU thing. MSAA occurs only within the GPU itself and doesn't even know that anything outside of the video card exists. Yes, MSAA eats up tremendous amounts of GPU bandwidth, but the color depth setting doesn't affect this because we set up the GPU to internally use 32-bit framebuffers for all of its processing. We use 32-bit framebuffers because the BGRA8888 format is a universal format for all modern GPUs and is highly optimized for them.

The color depth setting has zero performance impact with OpenGL or the GPU since our OpenGL renderer generates the 3D layer on the GPU alone. What the color depth setting affects is the maximum color depth that the CPU-based 2D engine allows for. Therefore, the performance difference that you are seeing between 18-bit/24-bit and 15-bit is the 2D engine's pixel composition that is performed on the CPU.

You've said before that you run an Intel i5, correct? That means that your CPU is running the SSE2-accelerated pixel compositor. 18-bit and 24-bit colors are processed as 32-bit integers, which means that the SSE2 pixel compositor can only work on 4 pixels at a time. However, 15-bit colors are processed as 16-bit integers, which means that the SSE2 pixel compositor can work on 8 pixels at a time. In short, the SSE2 pixel compositor can work through 15-bit colors twice as fast as 18-bit and 24-bit colors.

> Thank you for the in-depth explanation. I believe the Dolphin team have run into the same issue, where improving accuracy in one area exposed inaccuracies in another area, ironically reducing compatibility. In Dolphin, enabling some options like Dual-Core can cause subtle bugs that the user might not notice until their save is corrupted or their game crashes, which I was hoping to avoid with DeSmuME.

It's not just a Dolphin thing -- its an "all complex system emulators" thing. This issue becomes increasingly more difficult to balance when you start adding all sorts of fancy emulator features that never existed on the original system, and then trying to remain perfectly compatible on top of that. It's easy to make a super-duper accurate emulator if you're emulating a very simple system and if you're not planning on adding any extra features to it. DeSmuME is the exact opposite of that, in which we are emulating one of the most complex systems out there AND adding an extremely rich feature set on top of that. So yeah, accuracy and compatibility are a difficult thing to balance in DeSmuME.

Let's put things into perspective here: With that Intel Core i5 CPU of yours, you can decide to emulate a Nintendo DS system using DeSmuME with all sorts of fancy features enabled and remain reasonably compatible with the vast majority of the NDS library, or you can decide to perfectly and accurately emulate 1972 Pong using DICE without any extra features at all. Guess which emulator will stress your CPU less? That's right -- DeSmuME.

**Comment by rogerman** [comment]
For @Jules-A:

> I know this is kind of off-topic but there was a difference between 18 and 24bit on my old 5750, though still very tiny compared to 15 to 18bit. On my RX570 the difference between 15bit and 18bit is large (larger than it was on my 5750, though other settings are higher) but 18 to 24bit is practically nil. I don't think its bandwidth, seems more like it's my CPU limiting it.

OpenGL sets the GPU to use 32-bit BGRA8888 framebuffers internally for all of its rendering. When the 3D layer needs to be read back to the 2D engine, this involves reading back the rendered 3D framebuffer from the GPU back to the CPU.

When you set the color depth to 24-bit, OpenGL simply Y-flips the 3D framebuffer on the GPU before it reads it back to the CPU. However, if the color depth is set to 18-bit, OpenGL does a Y-flip and a color conversion from BGRA8888 to RGBA6665 before reading the framebuffer back to the CPU. This color conversion uses a shader to do this, and so is dependent on the shader performance of your GPU.

A Radeon 5750 only has 720 shader units that operate at 700MHz, which isn't the greatest shader performance out there. But trust me -- it's still better to do color conversions here than on the CPU, for which color conversions are MUCH slower there.

A Radeon RX570 has 2048 shader units that operate at 1168MHZ, which is much much much faster than a Radeon 5750. This is why the performance difference exists between 18-bit and 24-bit color modes on your different GPUs.

As for the CPU limitation thing: See my response to @extherian's third point, which explains why 15-bit runs twice as fast as 18-bit and 24-bit.

> If I can remember correctly, I actually saw a tiny decrease in performance on my system going from 12 to 15 but going from 12 to 18 slightly increased performance. Going from 18 to 100 increased performance by less than 12 -> 18.

Odd, but not surprising. The JIT is free to optimize blocks of instructions however it wants, and so it is very possible that certain games may use instructions in ways where the JIT magically runs faster with a block size limitation of 12 because having a larger block size limitation of 15 can slightly throw it off its optimizer. Because of the way JIT's optimizer works, I wouldn't take any of these performance comparisons based on the JIT block size as absolute benchmarks -- they are more like performance indicators that can make good rules-of-thumb.

**Comment by zeromus** [comment]
Actually, my old analysis stands. If anyone figures out what this is useful for, we'll turn it on as a game-specific hack

**Comment by Jules-A** [comment]
> Actually, my old analysis stands. If anyone figures out what this is useful for, we'll turn it on as a game-specific hack

I think it not being exposed on Windows means no-one has really tested it. Having it enabled by default could have some nasty side effects. Maybe just expose it as a hack and leave it default disabled until it's been properly tested? It might be helpful for performance reasons, I haven't tried it but it does sound pretty interesting.

**Comment by zeromus** [comment]
It only helps for compatibility reasons.  This is a poor way to investigate and evaluate hacks. I'm not going to double down on the slop in the code by putting it in the UI. The new policy is to debug a game, discover a hack will fix it, and then put it in the code without wiring it up as an option any further than tying it to the game ID to enable the hack.

**Comment by Jules-A** [comment]
Oh, I just re-read a bit more of the comments where rogerman went in to more detail. I was a bit confused by >we'll turn it on as a game-specific hack
but now I'm pretty sure you meant "turn it off" instead.

So basically what rogerman originally said?
>Leave Rigorous 3D Rendering Timing as a CommonSettings option, but have it ON by default. Also make Hotel Dusk be a per-game hack that overrides the setting to OFF. No UI changes will be necessary in either the Cocoa or Windows ports. Then let the users test games for a while until someone reports a problem. Or maybe no one will report problems. Well... more testing would be a safe bet, either way.

**Comment by zeromus** [comment]
No, we'll turn it ON as a game specific hack. It's the opposite of what rogerman said. The reason desmume defaults to having it off is because more games work that way. That won't change. Rogerman says he tested lots of games with it on. More people have tested more games with it off. The only reason the option exists is because at the time I did it, I was uncomfortable with the timing hack of non-rigorous timing and thought more games would need rigorous timing to work. But it turns out that isn't the case.
