### ISSUE TITLE
OpenGL issues from 7080e21

### ISSUE THREAD

**Issue by Jules-A** [TASVideos/desmume#240]
7080e21 Causes OGL Old to show most things as black. OpenGL 3.2 is fine. Running RX570 with 18.12.2 drivers in Windows 10. Occurs in all games I have.
![image](https://user-images.githubusercontent.com/1760158/50173589-e7941300-0332-11e9-9b4a-7e9babad6e00.png)

[A user on Reddit](https://www.reddit.com/r/emulation/comments/a7bfcw/desmume_performance_update_for_gpus_with/ec20vpq/) running Intel Celeron N2840 iGPU is unable to run OGL at all (details in link).

**Comment by rogerman** [comment]
The reddit user is having an issue because of their Intel HD Graphics iGPU, which only has a GL_MAX_VARYING_FLOATS of 64. This older GPU's low varying float count is causing the Fog shader to fail to link, since the new Fog shader introduced in commit 7080e21 requires 66 varying floats.

It seems that 44% of users have GPUs with a GL_MAX_VARYING_FLOATS of 64 or less, so this is certainly a compatibility issue that needs to be addressed. I'll have to think about this one for a proper solution. In the worst case scenario, I might just have to bring the old Fog shader back to support these older GPUs.

**Comment by zeromus** [comment]
Why are those big arrays even varyings? they only depend on uniforms. can't they be precalculated and set as uniforms for the fragment shader?

**Comment by rogerman** [comment]
Well of course they can be precalculated into uniforms before sending to the fragment shader.

The only reason I did it like that was as an in-between solution for unrolling a really long loop without having to change the existing algorithm too much. But this was mainly a proof-of-concept for myself to see if I could do something even better: precalculating the values into constants.

**Comment by Jules-A** [comment]
Hmm... the new depth changes in 37afaef changed the issue I'm seeing with OGL Old.
[NDS-style depth off](https://user-images.githubusercontent.com/1760158/50178129-a6096500-033e-11e9-85ec-ca1c30a1c687.JPG
)
[NDS-style depth on + 24bit color depth](https://user-images.githubusercontent.com/1760158/50178142-ac97dc80-033e-11e9-92bb-1416ad982693.JPG)

**Comment by rogerman** [comment]
Reference commit 5895248, which truly fixes (hopefully) all of the issues with OpenGL Old.

**Comment by Jules-A** [comment]
I can confirm it fixed it for me.
