### ISSUE TITLE
[OGL 3.2]Fog doesn't render with MSAA enabled and Special Zero Alpha Blending disabled

### ISSUE THREAD

**Issue by Jules-A** [TASVideos/desmume#246]
In Pokemon Platinum, may happen in other games but haven't tested.
Regression from 21a3fae. Only OGL 3.2 is affected.
RX570, 19.1.1 driver.

[desmume.ini.txt](https://github.com/TASVideos/desmume/files/2762399/desmume.ini.txt)

**Comment by Jules-A** [comment]
@rogerman  While most fog seems fine, it's still a bit glitched in one area I know. This area always had the glitched black outline with MSAA enabled but now things get weirder (easier to show than explain).
https://youtu.be/vmLKBgJGf9Q?t=5

**Comment by rogerman** [comment]
Looks like Edge Mark doing its thing. Can you confirm that this is, in fact, the Edge Mark effect by toggling the Edge Mark option?

If the "glitched black outline" is, in fact, Edge Mark, then I would need proof from a hardware NDS to know if this is actually a real graphical glitch.

**Comment by Jules-A** [comment]
I have Edge Mark disabled, with it enabled it just gets bigger.

**Comment by rogerman** [comment]
@Jules-A: A few questions.

1. Does the "glitched black outline" occur when you run this scene using SoftRasterizer? OpenGL isn't intended to be a super-duper accurate 3D renderer, and so minor glitches like this are deemed acceptable under OpenGL.
2. Does the "glitched black outline" occur when you run this scene at the native resolution (1x GPU Scaling Factor)? All graphical glitches also need to be tested at the native resolution in order to ensure that it isn't related to running the 3D at some non-native resolution.
3. Aside from simply involving Fog, is this "glitched black outline" issue related to this ticket in any other way? If not, please open a separate ticket so that we can address this issue properly, thanks.
4. What does the SZAB issue have to do with this particular ticket? Again, please open a separate ticket so that we can address this issue properly, thanks.

**Comment by Jules-A** [comment]
The black line has been a glitch as far as I can remember, actually, it appears you've fixed it with your last commit but it reappears when changing any settings. There is another glitch that didn't occur before 21a3fae, if you can't see it try looking at the video in a larger size and look for the change in whites, this also seems to happen only when loading an old savestate or changing a setting. I guess I can create a new issue for it now I understand how it occurs.
