### ISSUE TITLE
Monster Trucks DS (E) - Top screen is not cleared correctly on both render

### ISSUE THREAD

**Issue by DarkSwan86** [TASVideos/desmume#25]
Start a race and then pause it with Start. Press Select and you will go back to the menu. The top screen is not clearly corrected and show the cars from the race in front of the title.

![0467 - monster trucks ds e __19687](https://cloud.githubusercontent.com/assets/24975273/21742154/02f8987a-d4e9-11e6-8d6c-ded62ad08660.png)

--- ROM INFO ---
ROM game code: AMXP
ROM serial: NTR-AMXP-EUR
ROM chipID: 00001FC2
ROM internal name: MONSTERTRUCK
ROM developer: Majesco Sales Inc

--- PC INFO ---
CPU: Intel i5-4670K
GPU: AMD Radeon 7950
Driver version: Crimson ReLive Edition 16.12.2 (December 2016)
OS: Windows 7 x64

**Comment by zeromus** [comment]
This is discussed at length in the code, since we'll need to solve this better later, but the basic problem is that the game illustrates a huge flaw in our organization for emulating 3d. The game depends on changing the visible results of rendering solely by changing the clear image without sending any new geometry. This is a really unusual thing to do, but once you see it happening, it seems reasonable enough. In particular the game changes the clear image (the logo) to include an all-near depth surface which causes the trucks to get occluded by it. But the trucks aren't re-rendered and the current code won't have anything triggering it to do a refresh of the framebuffer.

The commit hacks it so games with clear images continually redraw the framebuffer even when the 3d geometry isnt updated.
