### ISSUE TITLE
Broken audio in Pokemon Black when using external bios + external firmware

### ISSUE THREAD

**Issue by windwakr** [TASVideos/desmume#258]
If I enable external bios and external firmware(but not "boot from firmware") the audio is completely broken in Pokemon Black. If I leave "emulate SWI with BIOS images" unchecked the console gets spammed with messages like
>Invalid SWI getPitchTab: FFFFFD16

If I enable "boot from firmware" then the audio works perfectly fine.

I've tested some nightlies on the site and it appears to have first appeared in the "2018/11/17 – git#91526e6" one. Just taking a glance at commits, there appear to have been some that touched the firmware loading in the time between that nightly and the previous.

**Comment by zeromus** [comment]
SWI bios sounds like my bug. changes to firmware config sounds like rogerman's bug. rogerman, send it to me if you don't want to deal with it.

**Comment by rogerman** [comment]
Most likely caused by the reordering of firmware loading in commit e27cc87.

**Comment by zeromus** [comment]
Seems like the only way this error message happens is with a mixup of arm7 and arm9? Maybe there's just a little snafu with routing the right file or function pointers to the right place and it's an easy fix

**Comment by rogerman** [comment]
Try the build for commit fe9541b. I've reordered the write to REG_WRAMCNT so that it must occur before the firmware unpacking step, just like it was before commit e27cc87.

@windwakr: AFAIK, the flow of the code seems to be correct, and so I don't see a big reason to change the ordering of firmware loading any further. However, I did notice that old .dfc files may not work correctly with the recent firmware code changes. If you are experiencing issues with loading external firmware user settings, then try removing the firmware.dfc file in your Battery folder and see if that fixes the problem.

Now... if you are still experiencing issues with commit fe9541b using a freshly generated .dfc file, then I will be stumped at that point and will need to pass this issue along to @zeromus.

**Comment by windwakr** [comment]
That fixed it.

**Comment by rogerman** [comment]
What fixed it? Did commit fe9541b fix it? Or did regenerating the .dfc file that fix it?

**Comment by windwakr** [comment]
Ah, sorry. The commit fixed it. I don't have the setting checked to load firmware settings from file.

But I've just noticed that booting from firmware is now broken.
>ARM7: Undefined instruction: 0x1C20E003 PC=0x03810004
Fresh ini, only enabled the external bios, external firmware, and "boot from firmware".

**Comment by rogerman** [comment]
That is the "correct" behavior. If you try booting from firmware without using the .dfc file, then it's not surprising that a firmware boot error would occur. Before, doing a firmware boot would always force the .dfc file to be used, regardless of the "Load User Settings From File" setting. Now, the "Load User Settings From File" setting is respected, even though it causes an error.

When not using the .dfc file, you are using DeSmuME's own firmware settings, which might be clobbering some of the legitimate firmware code that was loaded previously.

Options to fix:
1. Go back to forcing firmware boot to using the .dfc file, thereby avoiding unnecessary clobbering of legitimate firmware data. In this case, it would make sense to completely remove the "Load User Settings From File" setting, as this would be automatically used whenever the "Boot from firmware" setting is used. This is the easiest solution.
2. Send a flag to NDS_InitFirmwareWithConfig() that tells it that we are doing (or have already done) a firmware boot, and use that flag to prevent certain portions from loading. Now.... which specific portions should be skipped... that would require a whole bunch of testing to figure out. This is a much more involved fix, but would be better overall.

Oh well. @windwakr, this issue is fixed. If you still really want to boot from firmware without using the .dfc file, then please open a new ticket for that specific issue, thanks.

**Comment by rogerman** [comment]
Commit c6269ca now allows you to successfully boot from firmware without having to enable "Load User Settings from file".

**Comment by Wallack** [comment]
Hello windwakr is there any way i can Contact you? Is regarding some nwn stuff you might be able to help me with.
