### ISSUE TITLE
Booting from firmware without loading the .dfc fails to actually boot

### ISSUE THREAD

**Issue by Peduls** [TASVideos/desmume#259]
Checking the "Boot from firmware (like the NDS)" option results in a white screen. Without making any changes to my config I launched several different games with both the newest nightly build and the second newest. (DeSmuME_git#42817475 and DeSmuME_git#fe9541b4) The former loaded the BIOS without any issues, while the latter resulted in a white screen for every game.

**Comment by rogerman** [comment]
You need to also enable "Load User Settings from file" in order to make firmware boot work.

**Comment by Peduls** [comment]
Oh. In previous builds I didn't have to have a separate save file for my firmware settings.  Was that part of the changes made in git#fe9541b?

**Comment by rogerman** [comment]
In previous builds, when enabling "Boot from firmware", the separate .dfc file was ALWAYS used whether "Load User Settings from file" was checked or unchecked, since it was hard-coded to force the .dfc to be used for firmware boot.

In the newer builds, this is no longer the case. "Boot from firmware" and "Load User Settings from file" are now intended to be completely separate options. However, there is a bug where using "Boot from firmware" won't work unless "Load User Settings from file" is checked because, right now, using DeSmuME's internal firmware settings will erroneously overwrite the real firmware data that is necessary to boot, hence the white screen.

Sigh... I suppose that this issue will need to be addressed sooner or later, so I'll look into it shortly.

**Comment by Peduls** [comment]
Ah, that makes sense. In any case, thank you for your help and hard work on this emulator.
