### ISSUE TITLE
Improve RTC emulation

### ISSUE THREAD

**Issue by aerkiaga** [TASVideos/desmume#280]
Currently Desmume isn't compatible with [newlib](https://github.com/devkitPro/newlib)'s time() function, which does work on no$gba and real hardware. Thus, Desmume's RTC hardware emulation could be improved to the benefit of many homebrew DS games.

**Comment by aerkiaga** [comment]
This seems to be the code that reads the current time:
```C
long long value;
   asm volatile ("mov w0, %w1; mov x1, %2; " AngelSVCInsn " %3; mov %0, x0"
         : "=r" (value) /* Outputs */
         : "r" (reason), "r" (arg), "n" (AngelSVC) /* Inputs */
         : "x0", "x1", "x2", "x3", "x17", "x30", "memory", "cc"
           /* Clobbers x0 and x1, and lr if in supervisor mode */);
  return value;
```

`reason` is set to 11 (`AngelSVC_Reason_Time`).
`AngelSvcInsn` is a symbolic constant for `"hlt"`.
`AngelSvc` is a symbolic constant for `0xF000`.

**Comment by aerkiaga** [comment]
Looks like it puts the processor in Debug mode and passes some parameters somewhere.

**Comment by aerkiaga** [comment]
The obtained time is the time when the program was started, for every call to the function.

**Comment by zeromus** [comment]
we’ve known about this for years. there’s some reason it works this way, you might find an old discussion online somewhere. it’s like, it depends on the rtc interrupt which we don’t emulate or some complicated reason. maybe due to it being a terrible idea due to the mismatch between emulation time and real time which would be broken immediately. i recall arguing with the authors and telling them to do it differently, perhaps to poll the time instead of keeping it with interrupts, but either they never did or had their reasons for not doing it.

**Comment by aerkiaga** [comment]
Thank you. I sure did not expect that... Well, I might leave this issue open in case somebody comes up with  a way to solve it without compromising other stuff.

**Comment by aerkiaga** [comment]
Ok, I went through the code. I was wrong, it's not newlib thw one that gets the time. It's libnds itself. At initialization, it gets the current time by directly interfacing with the RTC; that's why the returned tiem was always the time when the program was started. Afterwards, it uses an IRQ (`IRQ_NETWORK`, or "serial interrupt mask"), incrementing the time in seconds. This apparently doesn't work on Desmume.

**Comment by zeromus** [comment]
I have a better memory now of leaving the irq unimplemented in order to force libnds to do it differently. just pause another emulator for a few minutes and resume it. what should the rtc say? with the irq approach it is now out of date. also consider this: load an old savestate. with their approach, the rtc can never get synchronized because it’s tally is too old and low.

**Comment by aerkiaga** [comment]
Now it all makes sense. I'll close this issue, thanks. Libnds is a much smaller beast, so I might as well rewrite some of it and recompile for my own purposes (or maybe send a PR, would be great).
