### ISSUE TITLE
how to force to use gles rather than desktop GL on arm platforms

### ISSUE THREAD

**Issue by Askmewho** [TASVideos/desmume#296]
Hi, I want to try opengl 3.0 ES (if its possible) rather than 2.1 Desktop GL..

I should recompile my sdl2 without opengl and then compile this project?

**Comment by zeromus** [comment]
You're probably not going to get any help since there's no linux users paying attention to this project right now. And at that----you should give up. We don't have a GLES renderer. We use GL directly, not through SDL, and it takes nontrivial rewriting to make GL stuff work in GLES. So I'm just gonna say... nope. Give up.

**Comment by zeromus** [comment]
Although I should mention, there are people compiling desmume for android all the time. You should go ask their projects. This isn't the project to ask.

**Comment by Askmewho** [comment]
ok @zeromus .. its a bit odd than my 2.1 gl profile doesnt match even the soft renderer. thanks anyway

**Comment by zeromus** [comment]
define "match"? each renderer has its own strengths, weaknesses, flaws, and warts

**Comment by Askmewho** [comment]
Nothing... its just than on soft it runs better than on gpu acceleration under 2.1 profile. Thanks anyway.

**Comment by zeromus** [comment]
desmume's GL renderer is NOT intended for speed. it's intended for a certain type of devices with pathetic CPUs, and ALL devices when rendering at increased internal resolution--and to keep around so that it has different bugs than softrasterizer. You may think that hardware accelerated rendering is an obvious win for speed, but it isn't. The nintendo DS gpu is weird, and emulating it with certain classes of conventional GPU hardware is making it bend over backwards.
