### ISSUE TITLE
Xbox Wireless Controllers connected via Bluetooth do not work.

### ISSUE THREAD

**Issue by Noxillio** [TASVideos/desmume#300]
In previous builds, it has worked perfectly.

**Comment by zeromus** [comment]
desmume's input logic hasn't changed in years. You must be mistaken about previous builds, accidentally conflating it with old builds, which you would have tested on old dates, on old computers, before whatever happened to your bluetooth drivers or other system gaming software to make it stop sending directinput data correctly.

**Comment by Noxillio** [comment]
I just used it a couple hours ago using the 0.9.11 available on desmume.org.

**Comment by zeromus** [comment]
then you need to configure your gamepad in the new desmume same as you did in the old one. copying over the ini file should work. desmume has no idea what controller you're using, or how it's connected. it's not possible for it to break and it's not possible to fix it because it just uses whatever windows reports.
