### ISSUE TITLE
Permission to add Desmume to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [TASVideos/desmume#314]
Hi there,

we would like to seek your permission to include Desmume as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by zeromus** [comment]
thanks for checking. no problem. do it.

**Comment by twinaphex** [comment]
Thank you.

**Comment by twinaphex** [comment]
Hi there @zeromus ,

wanted to inform yuo that this finally happened.

https://store.steampowered.com/app/1227467/RetroArch__DesmuME/

Also, I saw that an invitation was open for the Desmume repo, but it expired. Would I perhaps still be allowed to receive such an invitation? Perhaps with an arrangement like that, we could make this repo the upstream repo that the libretro CI uses for Desmume (and this would then get pushed to Steam as well).

**Comment by zeromus** [comment]
1. Can you show me what you would want to push to this repo in order to facilitate whatever you've got going on? I don't mind giving people commit permissions but I don't have any idea what you'd do with them. You're welcome to add your own "frontend" but modifications to the core right now will probably be jealously critiqued.... hit and run game-breaking commits are becoming a real threat.
2. can you take me out of the credits list on the steam page? That's your business, not mine personally. It's probably smart to credit "desmume team" and I can't disclaim their crediting anyway so you should leave that one.
