### ISSUE TITLE
OpenGL Display Mode overly uses RAM until there is none.

### ISSUE THREAD

**Issue by UghThatGuyAgain** [TASVideos/desmume#332]
I was attempting to stream my screen over Discord when the issue of consistent white flashes on both the streaming end and the client end came along. To try and fix this, I decided that it would be easiest to look for a different rendering method or a display method within the config tab that would fix it. Nothing was working, except for changing the display method to OpenGL. However, after doing so, my RAM usage spiked and kept increasing, even while not running a game. I likened this to possibly there being no garbage collecting implemented, but I've yet to look at the code and I'm certainly no C++ mastermind. I'm running on an i7-7700HQ processor with a GeForce 1050 and 16 GB of ram. 

Similarly, the call I was in on Discord was crashing, and I likened this to possibly Desmume overwriting memory that it was using, as I tried to disconnect and reconnect to the call and the entire application crashed.

Obviously, as I said, I'm not a C++ user nor have I done extensive research into the code behind Desmume, but I'll take a look to see if I find anything that could be causing the issue. Thanks so much in advance, and please let me know if this is an issue only I am having.

**Comment by zeromus** [comment]
Other people should have encountered this if it's a desmume problem.

I've checked the code for leaks, and saw none. It doesn't leak without bound on my system. Occam's razor says your GPU driver is bugged. Upgrade or downgrade it. 

If desmume causes discord to crash, then the problem is DEFINITELY your GPU driver's fault. Although it is possible that desmume is stomping its own memory, the GPU driver should not be vulnerable to failure from that. However if the GPU driver is internally glitch, any correlation between programs could bring down the driver and bring down the program. Also, if you change desmume to software rasterizer, there's no way it's stomping its own memory (the opengl display method is simple code).

Now after all that, I should say also, a faulty GPU can look like a glitchy GPU driver. That's especially likely if the driver is a normal nvidia one used by many people, but even supposedly stable drivers can have bugs due to other weird oddities about a system. So a faulty GPU is a high probability as well.
