### ISSUE TITLE
[feature request] drop DirectDraw display backend and sync scaler shaders for windows port. 

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#37]
Since DirectDraw is only for windows xp and doesn't have any advantage on modern OS. Drop DirectDraw display method make it possible to reuse the new implement scaler shaders on windows port.
 
If request accepted, I can help to remove DirectDraw related code.

**Comment by zeromus** [comment]
direct draw support won't be dropped. you're welcome to make rogerman's scalers work in the OpenGL display method.

**Comment by rogerman** [comment]
If I were you, I wouldn't attempt to do any changes to the Windows-port display code just yet. The OpenGL display backend in the Windows port works much much much differently than it does in the Cocoa port, and so porting all of the Cocoa port's features over to Windows as it stands now would be an extremely difficult task.

Lately, I have been doing a lot of refactoring work to create a generic client display view class (named "ClientDisplayView") that would make creating new display backends much easier to do across all platforms, but this code is currently in heavy flux due to said refactoring going on. The first implementation that will use the new ClientDisplayView class will be in creating a new Apple Metal display backend for the Cocoa port, since this will help be better develop the ClientDisplayView class API.

However, once the Metal display backend is complete, then it should theoretically become much easier to incorporate Cocoa's OpenGL display backend into the Windows port.
