### ISSUE TITLE
gdoverlay: inconsistent color type

### ISSUE THREAD

**Issue by kaptanultros** [TASVideos/desmume#405]
I'm trying to write a Lua script to display some text and images on-screen when running Golden Sun: Dark Dawn, and the text works fine, but whenever I try to load an image using gui.drawimage or gui.image, or gui.gdoverlay, I just get the error message in the title.

I've read that the FCEUX documentation will suffice for desmume lua scripting, but the example provided in that documentation just gives me an error: "attempt to index global 'gd' (a nil value)".

local gdstr = gd.createFromPng("myimage.png"):gdStr()
gui.gdoverlay(gdstr)

How can I load a PNG file and display it with Lua script? I've tried with transparency, without transparency, I've tried different formats (8 bits per RGB, 8 per RGBA, 16 per RGB, etc.), and I get the same "inconsistent color type" error every time.

**Comment by zeromus** [comment]
someone decided not to use the same lua version that is used by fceux, which contains all of the extra libraries, because they would rather use "standard" lua dlls. so you will have to go find an appropriate gd package for lua. experiment in standalone lua.exe first, it may make things simpler.
I don't know whether anyone has had any success doing this before. I might have, but would have forgotten.

**Comment by kaptanultros** [comment]
The two different messages were from using two separate calls.

gui.drawimage, gui.image, gui.gdoverlay each caused "gdoverlay: inconsistent color type".

Trying the example code's "gd.createFromPng" caused "attempt to index global 'gd' (a nil value)".

**Comment by zeromus** [comment]
you dont have a gdstr to send to gui.gdoverlay because you don't have gd, so none of this makes sense.

**Comment by kaptanultros** [comment]
When using just the documentation for FCEUX, it was not clear that a separate library was required for Desmume in order to load and draw an image.

Based on all the information I had found, everyone was saying "use the FCEUX documentation, Desmume mirrors it", so that's what I did.

The image functionality described in FCEUX's documentation did not work, and there was no similar documentation available for the Lua functionality of Desmume itself to clarify that another library was required.

**Comment by zeromus** [comment]
OK, what do you want me to say? You are forgiven for doing what you did because the situation's a mess? You're forgiven.
You still need to find the gd dll and figure out how to use it.
I am dissatisfied with this messy situation, and since the guy who made desmume use the lua dll is no longer around, I might revert it to work the same as fceux does. I'll think about it.

**Comment by kaptanultros** [comment]
I was simply trying to clarify the situation, because you said it made no sense. I apologize if this sounded like I was making a bigger deal than I was.

**Comment by zeromus** [comment]
What doesnt make sense is that you have nothing to send to gui.gdoverlay because you don't have gd to load an image, so you must have got both by sending nonsense to gui.gdoverlay in a code snippet you didn't share.
