### ISSUE TITLE
New build

### ISSUE THREAD

**Issue by FinecoFinit** [TASVideos/desmume#409]
Can we have it already?

**Comment by zeromus** [comment]
https://ci.appveyor.com/project/zeromus/desmume/history

**Comment by FinecoFinit** [comment]
@zeromus Thanks

**Comment by eeuq7mi** [comment]
**Thank the authors for continuely maintaining this project with great effort!**

Personally, I suggest put the following link in `readme.md`:
[Download the latest compiled version](https://ci.appveyor.com/project/zeromus/desmume/build/artifacts)

I think perhaps this is better than a simple "Building Pass" icon: [![AppVeyor CI Build Status](https://ci.appveyor.com/api/projects/status/abfd7jm09wnmxyvu?svg=true)](https://ci.appveyor.com/project/zeromus/desmume). 
Most people go to the `release tab` or `desmume.org` and only find a very old version in the year 2015.

**Comment by zeromus** [comment]
I changed the link. Maybe you will like it more.

**Comment by eeuq7mi** [comment]
Thank you very much!
By the way, **the big green download button** on [sf.net](https://sourceforge.net/projects/desmume/) still attract about 31,000 people every week to download the old version in the year 2015.
![download](https://user-images.githubusercontent.com/76865770/104403510-9d260480-5593-11eb-8158-7eda1cd8d941.png)

To be honest, I just found the new build link in this issue. I know this project for many years, but I always didn't notice the new build link (I'm not familiar with `ci.appveyor.com` and I don't have enough time to compile) . I just kept using the old version in the year 2015.

**Comment by zeromus** [comment]
I can't figure out how to make sourceforge stop offering that. I fiddled with it a bit to try to direct people elsewhere.
That version still has files appveyor doesn't.
I pretty much have my finger on the pulse of how many people are shortchanged by using a 5 years old version of desmume, and it isn't so many that I can't say "use a newer version" to each of them who didn't figure it out on their own. So since it is impossible to make sourceforge always point to the newest version any more than I already do, I will leave it as it is (since I can't do anything different)

**Comment by eeuq7mi** [comment]
Thanks for reply. 
My goal is to reduce issue that caused by using old version like [this](https://sourceforge.net/p/desmume/bugs/1727/).
Yes, it's impossible to make sourceforge always point to the newest version.

---
The following may be helpful (if not, please ignore), but only for stable version:
**[Method 1]**
Upload a newer version, and then set it as default download.

[How to manually set the “default download” file in a Sourceforge project?](https://stackoverflow.com/questions/6777327/how-to-manually-set-the-default-download-file-in-a-sourceforge-project)

In the `Files` tab of the project, click the "i" button:
![1](https://user-images.githubusercontent.com/76865770/104421308-23534280-55b6-11eb-92ea-4d4d877f5073.png)

Set default download for each platform:
![2](https://user-images.githubusercontent.com/76865770/104421420-47af1f00-55b6-11eb-9344-ce3fe22b1192.png)

<br/>

**[Method 2]**
Use "GitHub Releases Integration" under the  `Files` tab.
![3](https://user-images.githubusercontent.com/76865770/104422366-a3c67300-55b7-11eb-85a8-57763fe71997.png)


> This GitHub release integration will copy any new releases from the GitHub repository into this project on SourceForge. Whenever you make a release on GitHub, you can have the files on SourceForge too.

**Comment by eeuq7mi** [comment]
Also, pin this issue to the GitHub issue tab may be helpful.
[How to Pin an issue to your repository](https://docs.github.com/en/enterprise-server@2.20/github/managing-your-work-on-github/pinning-an-issue-to-your-repository)

**Comment by zeromus** [comment]
Your goal is impossible. People download desmumes packed with other files from youtube links. Give up.
Sourceforge won't let you pick NO default download. Github releases are awkward. The only way these two could be "improved" from your point of view would be to remove all downloads entirely.

**Comment by HoratioVex** [comment]
@zeromus: To offer a converse experience from a user, just yesterday I invested what I consider a reasonable amount of time into updating my (Windows) Desmume from 2018 and ultimately gave up. That's because a) the appveyor build isn't signed, so I get a nagscreen popup every time I try to run it. There used to be a buildbot maintained by a contributor, it wasn't an issue there.

b) It requires a new VS2019 DLL, and the only link you offer on your github post is to a github server that downloads at 20kb/s, and even then I don't know whether I'd get the DLL or another installer I don't want.

At that point I figured my old version is probably good enough.

**Comment by zeromus** [comment]
a) The only buildbot we had was orphis's and I really doubt he SIGNED builds. Anyway I have zero sympathy for overzealous security software. Desmume will not be signing its builds.
b) Life is too short to be mirroring files just in case github is slow one day. If github is unusably slow then a lot of people have many much more serious problems at that time than not being able to download a gaming prereqs file. You can find "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019" elsewhere
