### ISSUE TITLE
Firmware factory reset

### ISSUE THREAD

**Issue by NicknineTheEagle** [TASVideos/desmume#428]
On a real DS, it is possible to reset firmware to factory default and bring up the initial setup screen ("Before you begin...") again by removing the battery for a minute and putting it back in. Is there a way to simulate this on an emulator with a firmware ROM? I've tried zeroing out the last 0x600 bytes in firmware ROM but that's not quite it, it brings up "System settings have been lost" screen (and crashes Desmume when I try to calibrate the screen).

**Comment by zeromus** [comment]
you will probably get more mileage by asking this on a melonds thread. If I had to guess, the firmware will reset itself if the RTC was set to its near-initial value (1970 or 2001 or something like that). That's the only way I can think of that it would know that the power had been lost.
As a practical matter, you simply need to
1. Delete your .dfc file
2. and/or dump an unmodified firmware file
In order to reset things in desmume

**Comment by NicknineTheEagle** [comment]
Turns out it's indeed related to RTC, thanks, Arisotura! Bit 7 in status register 1 indicates that time was lost.

**Comment by zeromus** [comment]
ok, well, now the mystery is solved. Is there anything else you need here? I am not sure I care to "support" this in desmume. It's will create a bunch of junk code for a rarely needed weird special case.

**Comment by NicknineTheEagle** [comment]
I guess that's all. It would be nice to have this in some way but I'm not sure if there's a nice way to implement this in the future, though. Maybe if we RTC override is ever implemented, this can be worked into that somehow.

**Comment by zeromus** [comment]
ok good idea.
