### ISSUE TITLE
Can't Save Settings to desmume.ini

### ISSUE THREAD

**Issue by eeuq7mi** [TASVideos/desmume#442]
Firstly, thanks for providing this excellent project!
Here I want to report a problem. 

**OS:** Win 8.1 x64

# Bug
1. Download commit `9d8332d` through [appveyor](https://ci.appveyor.com/api/buildjobs/x3hmry0kf1jqk2rx/artifacts/desmume%2Fsrc%2Ffrontend%2Fwindows%2F__bins%2FDeSmuME-VS2019-x64-Release.exe), and place the exe in an empty folder. (Make sure no existing `desmume.ini` in the folder.)

2. Run the emulator, and change some settings.
3. Close the emulator.
4. Strangely, it doesn't save its setting to `desmume.ini`. Instead, it create an **empty folder** named `desmume.ini`.
5. Reopen the emulator. And all the changes in setting have been discarded.

# Workaround
Use commit [4b77e9b](https://github.com/TASVideos/desmume/commit/4b77e9b77ae53fe8476df6ad90ca429caf41bc6a), which doesn't have this bug.

**Comment by zeromus** [comment]
This is what happens when you fix bugs in japanese language support; you create other bugs

**Comment by eeuq7mi** [comment]
Bug fixed. Thanks!

**Comment by FrankHB** [comment]
This is not Japanese specifc. Assumptions on stupid Win32 path encoding schemes are almost always defects.

But it is not _that_ difficult to do right ([1](https://github.com/FrankHB/YSLib/blob/master/YFramework/source/YSLib/Service/FileSystem.cpp#L106) [2](https://github.com/FrankHB/YSLib/blob/master/YFramework/source/YCLib/FileSystem.cpp#L911)) (event a bit more potable than Win32), althouth the answers in [the SO question you see](https://stackoverflow.com/questions/1530760) has all kinds of nasty bugs (besides TOCTTOU ones which can't be practically fixed within every filesystems).

**Comment by zeromus** [comment]
Why don't you fix the next bug like this that someone finds in this nasty codebase and then tell me it's not that difficult

**Comment by FrankHB** [comment]
I'd like to fix the upstream bugs at first, so there are less chances to see the bugs spread to all kinds of projects after being copy-pasted (though this issue seems not the case).

**Comment by zeromus** [comment]
What upstream bugs?

**Comment by FrankHB** [comment]
> What upstream bugs?

To list a few about this topic:

* Every answer of [the question referenced from SO](https://stackoverflow.com/questions/1530760) are buggy, more or less.
* C++'s `<filesystem>` has [quite a lot issues in the LWG list](https://wg21.cmeerw.net/lwg/issue?@columns=id,activity,section,status,title&@sort=-activity&@group=priority&@filter=status&status=&@search_text=fs.). Many C++ users are not satisfied with the status quo, or treating it totally wrong in design. (Although I think it still more correct to some other answers.)

I don't take it in a high priority because I have avoided most of such defective practice in my codebase at the very beginning. It is just still annoying when I meet the same bugs here and there, in many programs I'm daily using (esp. with some aged codebases). I may randomly fix a few of them in my spare time, but I have absolutely no magic power to cleanup all. Besides, I don't know whether the maintainers would treat them seriously.

Nevertheless, to find such a bug is still easier, whether you fix or not.

(Hint: A call to `mkdir` in `src/desmume/saves.cpp` seems a similar issue here.)

**Comment by TheTechn0mancer** [comment]
> Why don't you fix the next bug like this that someone finds in this nasty codebase and then tell me it's not that difficult

Damn 5 years later since I last checked and you still sound like an asshole
