### ISSUE TITLE
Legacy Intel iGPU (1st and 2nd generations Intel Core) - Both OpenGL renderers crash Desmume immediately on load ROM

### ISSUE THREAD

**Issue by pal1000** [TASVideos/desmume#45]
Since SVN 5195 (fec691b). Tested with Final Fantasy IV.
**_Console log_**:
````
DeSmuME 0.9.12 git#1e96e738 x64-JIT SSE2
- compiled: Dec 24 2016 16:16:18

Microphone successfully inited.
DeSmuME 0.9.12 git#1e96e738 x64-JIT SSE2
Attempting change to 3d core to: OpenGL Old
WGL OpenGL mode: hardware
OpenGL: Successfully created shaders.
OpenGL: Successfully created postprocess shaders.
OpenGL: Successfully created FBOs.
OpenGL: Successfully created multisampled FBO.
OpenGL: Renderer initialized successfully (v2.1.0).
[ Driver Info -
    Version: 3.1.0 - Build 9.17.10.4459
    Vendor: Intel
    Renderer: Intel(R) HD Graphics 3000 ]
GL display context pixel format: 4

ROM game code: YF4E
ROM serial: NTR-YF4E-USA
ROM chipID: 00007FC2
ROM internal name: FF4
ROM developer: Square-Enix

Slot1 auto-selected device type: Retail MC+ROM
Slot2 auto-selected device type: None (0xFF)
BackupDevice: size = 512 Kbit
CPU mode: JIT
JIT: max block size 15 instruction(s)
Already decrypted.
Loading C:\Software\NDS\Roms\Final Fantasy IV.nds was successful
Emulation unpaused

````

**Comment by pal1000** [comment]
Visual Studio debugger screenshots - Release build:
![desmume1](https://cloud.githubusercontent.com/assets/1138235/23553821/191eccce-002b-11e7-9cbc-c104f887d42d.png)
![desmume2](https://cloud.githubusercontent.com/assets/1138235/23553864/4581baf6-002b-11e7-9825-d3dedf7ad5d6.png)
![desmume3](https://cloud.githubusercontent.com/assets/1138235/23553865/45876d0c-002b-11e7-821c-8dd5c5567c52.png)
![desmume4](https://cloud.githubusercontent.com/assets/1138235/23553866/4588c710-002b-11e7-9a48-0221a57bb87f.png)
I can do a debug build if needed.

**Comment by zeromus** [comment]
Thanks for tracking down the first revision with the bug. I've debugged this too. Moreover I think it happens on nvidia drivers, intermittently. But that's rare and it's hard to prove. I could be wrong about it. I think something sketchy is happening and clobbering memory inside the driver so it later crashes at unrelated points.

I'll paste my notes from when I debugged it:

so for quite some time now, the opengl renderer has been uselessly broken for me. it crashes randomly--and frequently. i cut out all the opengl newer than 1.2 and found the isFBOSupported functionality appears to be the culprit. if i cut it out, the random crashes stop

willConvertFramebufferOnGpu isn't the problem

if i simply set isFBOSupported=false after willFlipFramebufferOnGpu and willConvertFramebufferOnGpu are finished being set, then the random crashes stop

commenting out everything controlled by if(isFBOSupported) in SetFramebufferSize() solves it, but then again, maybe that's because it doesnt render anything anymore

its the setup of the depthstencil texture that does it

if i remove the first glTexImage2D call (in CreateFBOs) then it works OK too. (it's later teximage'd by SetFramebufferSize())

i can also solve it by not setting that texture onto the FBO's depth attachment

or the stencil attachment. its when both are attached that there's a problem

i attempted not very hard to break out the depth and stencil textures but it didnt work for some reason i dont understand

by changing both arguments to the pertinent glTexImage2D calls to GL_DEPTH_STENCIL_EXT instead of GL_DEPTH24_STENCIL8 and GL_UNSIGNED_INT_24_8, the crash goes away. then again, it doesnt render anything either

tellingly, one place i get crashes more often than not is inside glDrawBuffer(GL_COLOR_ATTACHMENT1_EXT); // texGDepthID

wait, maybe it's in the clear above, where it clears the depth and stencil buffers. well anyway. interesting too

**Comment by pal1000** [comment]
Since I figured out how to build Mesa3D on Windows, I tried llvmpipe too, that can actually go ingame, but that has graphical glitches instead that makes things unplayable, but I guess that's another issue, possibly an external one.

**Comment by rogerman** [comment]
I've been doing a lot of fixes to legacy OpenGL lately, and I think I've managed to fix all the bugs.

Try git#917475b from desmume.org/download and see if that works out for you.

**Comment by pal1000** [comment]
Sorry, this didn't help. Both OpenGL modes still crash. The only improvement is that I no longer get crashes when switching from OpenGL Old to 3.2 and vice versa before attempting to boot anything. But I think this is not a very recent fix,
There is improvement with OpenGL Old and llvmpipe compared to recent days, but there are still some graphics corruptions. OpenGL 3.2 and llvmpipe is not affected, though if I don't set context with MESA_GL_VERSION_OVERRIDE and MESA_GLSL_VERSION_OVERRDE correctly I get an instant crash.
If you want to look into those graphics corruptions, Mesa3D builds for Windows are available [here](https://github.com/pal1000/mesa-dist-win).

**Comment by zeromus** [comment]
I've forgotten what system I tested it on when it was crashing for me every-single-time, but it's been stable on my main nvidia workstation for quite a long time now, and I'm pretty sure I saw this bug happening occasionally at least on this system.

**Comment by rogerman** [comment]
Please try commit git#7a018eb. It should now work for the Mesa3D 17.1.5 driver, as well as my own Nvidia 384.76 driver. It should also be available at http://desmume.org/download.

**Comment by pal1000** [comment]
llvmpipe renders correctly with both OpenGL modes now, Though I noticed Desmume doesn't use more than 50% of the CPU even if llvmpipe is used, probably the way multi-threading is done prevents utilization of more than 2 hyperthreads leading a potential under-performance. Anyway, back on topic as the crash when I use the GPU driver is still there.
Here are my system specs:
Dell Vostro 2521 Q1 2013;
CPU: [Intel Core i3-2375M](http://ark.intel.com/products/74259/Intel-Core-i3-2375M-Processor-3M-Cache-1_50-GHz)
GPU: Intel HD Graphics 3000
Driver Version: 9.17.10.4459.
Windows 10 Version 1703 build 15063.483.

**Comment by rogerman** [comment]
AFAIK, the OpenGL renderer related issues are fixed. As for the crashing issue, I can't reproduce any crashes now, but I'm using an Nvidia driver under Windows.

I have done testing on an Intel HD Graphics 3000 on macOS, and that doesn't have any problems, so it's most likely a Windows 10 driver issue. Or it could be your particular system. Unfortunately, I don't have any machines with an Intel HD Graphics 3000 running WIndows 10, so someone else will need to debug this.

**Comment by zeromus** [comment]
Without anyone else reproing it, I'm gonna call it, glitchy GPU. I suspect the problem is we were doing something sketchy or slightly undefined and some drivers dont handle it at all. Any particular driver version from any particular vendor may be liable to crash instead of doing something benign. Oh well. We just need to revisit this another day.

**Comment by Jules-A** [comment]
@zeromus Sorry for not mentioning, this happens on one i5 2400m laptop.

**Comment by zeromus** [comment]
bleck. Like, seriously, recent commits?

**Comment by Jules-A** [comment]
Not sure, I was testing my changes to the MSAA selector.

**Comment by zeromus** [comment]
That's recent enough for me. I guess it's still broken, but I'm still going to disbelieve it until I see more stacktraces

**Comment by Jules-A** [comment]
I can test with rogermans recent changes but I don't think I can just install VS since it's not my computer.

**Comment by zeromus** [comment]
You don't need to test with 1 recent change which has nothing to do with the problem, when the problem is years old, and the bug contains dozens of "see if this unrelated commit fixes it"'s and "no it doesn't"'s and in the meantime there have been 100s of other unrelated commits. That doesn't make any sense. However, I still want to see a modern stacktrace.

**Comment by Jules-A** [comment]
Okay... so you're gonna love this, whatever rogerman did recently sort of fixed it. By sort of I mean changing to OpenGL crashes, trying to change anything in the option windows, crashes. But if it's already set to OpenGL, it is able to run in OGL if you don't click anything until the intro has played. Everything at default settings other than the change of renderer.

Logs look pretty normal I think: 

> DeSmuME 0.9.12 git#44ac04df x64-JIT SSE2
> - compiled: Oct 31 2018 08:32:31
> 
> Microphone successfully inited.
> DeSmuME 0.9.12 git#44ac04df x64-JIT SSE2
> Attempting change to 3d core to: SoftRasterizer
> SoftRasterizer: Running using 4 additional threads. (Multithreading enabled.)
> WGL OpenGL mode: hardware
> Attempting change to 3d core to: OpenGL 3.2
> OpenGL: Successfully created shaders.
> OpenGL: Successfully created postprocess shaders.
> OpenGL: Successfully created FBOs.
> OpenGL: Successfully created multisampled FBO.
> OpenGL: Renderer initialized successfully (v2.1.0).
> [ Driver Info -
>     Version: 3.1.0 - Build 9.17.10.4459
>     Vendor: Intel
>     Renderer: Intel(R) HD Graphics 3000 ]
> 
> ROM game code: IPKE
> ROM crc: FFD28F00
> ROM serial: NTR-IPKE-USA
> ROM chipID: 00007FC2
> ROM internal name: POKEMON HG
> ROM developer: Nintendo
> 
> Slot1 auto-selected device type: Retail MC+ROM
> Slot2 auto-selected device type: None (0xFF)
> BackupDevice: size = 4 Mbit
> CPU mode: Interpreter
> Already decrypted.
> Loading F:\New folder\Pokemon - HeartGold.nds was successful
> Emulation unpaused
