### ISSUE TITLE
Ultimate Mortal Kombat: corrupted graphics on upper pause screen

### ISSUE THREAD

**Issue by windwakr** [TASVideos/desmume#46]
https://i.imgur.com/5zCWerg.png
The corrupted part of the graphics are the previous screen's graphics with a different palette.

I think this game is DMA'ing its upper pause screen background to 0x06210000, and any parts it tries to do at 0x06218000+ don't seem to take hold?

The intro screens use that same addresses, but VRAM is set up differently. Some pics of no$gba's IO map:
https://i.imgur.com/ejRR42o.png
https://i.imgur.com/VuIGSGV.png (no$gba doesn't show any of the upper pause screen correct)

Is this some sort of mirroring issue or something?

**Comment by windwakr** [comment]
Adding  `MMU_vram_arm9(VRAMBANK,VRAM_PAGE_BBG+6);` After [line 728 in MMU.cpp](https://github.com/TASVideos/desmume/blob/master/desmume/src/MMU.cpp#L728) seems to fix the problem.

But I'm not sure if that's 100% correct. DeSmuME's VRAM mirroring is a bit confusing. Why is it done this way?

**Comment by zeromus** [comment]
Because the NDS vram mirroring is confusing.

**Comment by zeromus** [comment]
OK, good detective work. 
This code could be done better by reimplementing it so that there is one function which approximates the digital logic directly, and then `probe` it about 1000 times or more to set up the page tables. Since this will be kind of slow, we'd want to then create a table of precomputed results, across a ~32bit key which is all the mapping bits combined. Unfortunately there are too many combinations to precalculate them all. In the meantime what we get is pretty "cargo culty" code which is kind of inside out and bizarre, but which--apparently--when implemented correctly as designed--somehow works.
