### ISSUE TITLE
 Lack Of Disco by Popsy Team graphics glitch

### ISSUE THREAD

**Issue by benderscruffy** [TASVideos/desmume#58]
http://www.pouet.net/prod.php?which=53963
on the first screen it is missing the disco ball on the top screen

**Comment by zeromus** [comment]
Cool, it works in 0.9.11. Some recent change in the matrix commands must have broke it (the geometry is appearing in a strange place and getting clipped)

**Comment by intact** [comment]
probably this change https://github.com/TASVideos/desmume/commit/66b5da1cdc5171f1f606e94f659811726cb4a39e

**Comment by zeromus** [comment]
are you guessing or did you bisect it? It's a good guess, but someone needs to bisect it

**Comment by intact** [comment]
It's bisect.

**Comment by zeromus** [comment]
Thanks. In particular, it's `power_geometry = FALSE` which breaks it.

**Comment by zeromus** [comment]
Looks like the problem is probably my waiting until the vblank to change the geometry engine power ("try powering on geometry"). By powering it on immediately, the problem is fixed. I'm not sure why I did it this way. We need to study further "Use SwapBuffers command once after enabling Rendering/Geometry Engine" from gbatek and why this is needed, and what it really does. Maybe specific mysterious things malfunction (but largely, things work) until the first swap happens? That probably doesn't need to be emulated. 

Check #31 when revising this code.
