### ISSUE TITLE
[feature request] assign configuration ini file from command line parameter 

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#7]
Just like PCSX2, to make it possible to have per game settings.

**Comment by rogerman** [comment]
Can you give a specific example of two games for which you want different settings? What settings need to be different and why?

**Comment by ppsspp-gamer** [comment]
For example "Mario Kart DS" is 3-D game perfect for OpenGL raster, 3x internal resolution, 2x texture scale. 

On the other hand "Castlevania - Dawn of Sorrow" is a 2-D game with a lot of 2-D effect, run much faster with SoftRaster, 1x internal resolution, 1x texture scale, and apply 2xBRZ filter. This game also need Advance SPU logic to fix audio noise and JIT block size 12 to fix sprite corruption.

When switch game from Mario Kart DS to Dawn of Sorrow, almost half of DesMume settings need to change.

**Comment by zeromus** [comment]
The only way this might happen in windows is by looking for an ini file with the same name as the game. I don't think a more portable solution is practical, but it would be possible if someone added yet another portable config file system, but unlikely. I won't be doing this.

**Comment by rogerman** [comment]
I disagree with this assessment. Here's the rundown.

- It seems more like there is a need for the internal resolution setting and texture post-processing options to be changed via the command line. These settings can now be accessed via the command line as of commit 60e71ce.
- You can use JIT Block Size 12 and Advanced SPU Logic for all games. The performance difference with JIT Block size 100 and Dual SPU Sync/Async is negligible.
- We are aware of Castlevania: Dawn of Sorrow having graphical issues when JIT Block Size is greater than 15. This is actually a symptom of a bug that needs to be fixed in the JIT engine, but I doubt that there will be any attempts to fix this bug anytime soon.
- We are also aware of Castlevania: Dawn of Sorrow having audio noise issues with Dual SPU Sync/Async. This may be a bug that needs to be fixed, or it may not be. Whatever the case may be, Dual SPU Sync/Async is more of a performance hack than anything else, and it isn't really a very good one. It doesn't net you any significant performance improvement. You're better off just using Advanced SPU Logic at all times.

The only thing left is applying the 2xBRZ filter, which is just a single menu option away. I don't consider this a major usability issue.

Therefore, I see that assigning a custom .ini file via the command line to be an unnecessary feature. In Windows, you can have your per-game command line options by setting them up as Windows shortcuts.

Closing, since this feature request is rejected.
