### ISSUE TITLE
[opengl] Misshapen 3d darkening overlay in Pokemon Heartgold

### ISSUE THREAD

**Issue by feliwir** [TASVideos/desmume#72]
Hey, the 3D Content in the upper screen is masked when going inside caves.
This is the wrong look:
OpenGL 3.2 & OpenGL old:
![image](https://user-images.githubusercontent.com/2104576/27654343-3bb121ec-5c42-11e7-8b7b-6309029603ca.png)

The correct:
Software;
![image](https://user-images.githubusercontent.com/2104576/27654372-56375766-5c42-11e7-993e-915b433572a3.png)

**Comment by zeromus** [comment]
please test in latest dev build from in-game save at this scene

**Comment by feliwir** [comment]
I don't have a development build at the moment. Will try to build one later today

**Comment by zeromus** [comment]
so save in-game

**Comment by rogerman** [comment]
The outer edge of the scene uses fog to fill in the remaining black pixels. In the v0.9.11 release and earlier versions, the OpenGL renderer doesn't support fog. However, the current revision does support fog. In fact, ever since r5166, the OpenGL renderer has supported fog.

Try using a nightly build.
