### ISSUE TITLE
[OpenGL] Super Mario 64 DS - Peach renders incorrectly

### ISSUE THREAD

**Issue by windwakr** [TASVideos/desmume#74]
![peach](https://user-images.githubusercontent.com/284886/28509757-319827a8-7012-11e7-81c7-e08fd798e5c9.png)
I've tested random builds back to ~r5450 and they all had this issue. 0.9.11 release renders her correctly. I don't have VS set up ATM, so I can't find out exactly where it started.

Also, the "Peach" signature on the letter seems to be blended wrong or something.

**Comment by zeromus** [comment]
Weird. Such big bugs you'd expect to be breaking everything. 
Maybe it is a strange use of the opaque vs translucent polyid which isnt well supported in ogl renderer

**Comment by rogerman** [comment]
That's exactly what it is. This issue is related to #24.

In v0.9.11, OpenGL's stencil buffer was used to store translucent poly IDs. But ever since r5372, we've been using the stencil buffer to try and fix shadow polygon rendering. Nowadays (ever since commit 5285131), we use the stencil buffer to store the opaque poly IDs.

This will not be fixed until a significant rework is done on the OpenGL renderer to support translucent poly IDs. This will take some time to figure out, since the most straightforward way to support translucent poly IDs is using the stencil buffer, but OpenGL only allows the usage of one stencil buffer at a time.
