### ISSUE TITLE
Mario Kart DS cut scene pixel shift when choosing GPU color depth 18 bit on AVX2 build

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#75]
## **This bug only happens in AVX2 build.**
 
steps to reproduce this bug:
(1) grab latest code from git
(2) change these two settings in "desmume.props" to enable SSSE3 and AVX instructions:
		<SSE_Level Condition="'$(SSE_Level)' == ''">40</SSE_Level>
		<AVX_Level Condition="'$(AVX_Level)' == ''">20</AVX_Level>
(3) make a release x64 build 
(4) run DeSmuME 
(4) choose config --> 3D setting --> OpenGL 3.2 render
(5) choose config --> 3D setting --> GPU color depth 18 bit
(6) run Mario Kart DS (US)
(7) start a match 
(8) you will see screen pixel shift in introduction cut scene

![screen-1](https://user-images.githubusercontent.com/8726272/28515107-f41b0d46-708e-11e7-8cc9-8404b787db9f.jpg)

My DeSmuME settings:
[desmume.ini.zip](https://github.com/TASVideos/desmume/files/1169269/desmume.ini.zip)

**Comment by rogerman** [comment]
Can't reproduce the issue with SSSE3 alone, so I'm pretty sure this isn't related to SSSE3.

This problem is probably related to AVX2. Try turning off AVX2. Does the problem still persist?

**Comment by ppsspp-gamer** [comment]
Yes, you are right. If I turn off AVX2, no more pixel shift. 
I have changed the tile of this issue.

**Comment by rogerman** [comment]
Try the latest commit with an AVX2 build.

Just like in issue #8, it seems like both pack and unpack instructions in AVX2 only work with 128-bit lanes within the 256-bit register, causing pixels to get swapped. Solution? Just add a vpermq instruction after every pack instruction in order to swap the pixels back to where they belong.

I think commit 4ba36cb should fix this issue. As far as I can tell, I don't see any other areas where pixels might get swapped.

**Comment by ppsspp-gamer** [comment]
This bug has been fixed, many thanks.
