### ISSUE TITLE
Commit 1ff91b7 break 3D rendering of Mario Kart DS  

### ISSUE THREAD

**Issue by ppsspp-gamer** [TASVideos/desmume#81]
After commit [1ff91b7](https://github.com/TASVideos/desmume/commit/1ff91b78416913f1d2fe7adbe2c04142f667ea60), all 3D rendered objects of Mario Kart DS disappear.

![screen](https://user-images.githubusercontent.com/8726272/28889717-7afd886a-77f7-11e7-95e1-3f0a9fe6494c.jpg)

Steps to reproduce this bug:
(1) grap latest code from github
(2) make a x64 release build 
(3) run Mario Kart DS
(4) all default settings except choosing OpenGL 3.2 renderer
(5) all 3d rendered objects disappear at character selection, cut scene, match .... etc.

my desmume.ini setting.
[desmume.ini.zip](https://github.com/TASVideos/desmume/files/1195006/desmume.ini.zip)

**Comment by rogerman** [comment]
Uggghhhh... I just knew that some compilers wouldn't like the template methods. Looks like I'll have to get rid of them...

**Comment by zeromus** [comment]
That's strange. I know any given compiler may have a problem with any given template but ordinarily it would be during the compiling and not during the running.

**Comment by rogerman** [comment]
The problem was that I changed SetupPolygon() from a virtual method to a template method. In LLVM/Clang and on Debug builds of Visual Studio, SetupPolygon() correctly pointed to OpenGLRenderer_1_2::SetupPolygon() and OpenGLRendererer_3_2::SetupPolygon() for classes OpenGLRenderer_1_2 and OpenGLRenderer_3_2, respectively. However, with Release builds in Visual Studio, SetupPolygon() in OpenGLRenderer_3_2 would point to OpenGLRenderer_1_2::SetupPolygon(), which is incorrect.

Looks like something to keep in mind, I guess.

**Comment by zeromus** [comment]
Weird. Sounds like something subtly illegal. If that's a compiler bug, we should strip it down and report it
