### ISSUE TITLE
World Destruction - 3D object flickering in outdoor scenes

### ISSUE THREAD

**Issue by rogerman** [TASVideos/desmume#97]
This is a regression from commit 1cc22ae.

Start a new game and watch the first scene. The characters and dialogue box will draw in one frame and then disappear in the next frame. This behavior alternates every other frame.

This bug occurs for both SoftRasterizer and OpenGL renderers.

**Comment by zeromus** [comment]
I believe this was caused by more accurate emulation of the matrix stack. Well, that's what the commit was, obviously. The game messes it up and then writes gxstat to clear the error flag; this should also clear (some? all?) of the matrix stack pointers. previously we cleared some. Changing it to clear all of them does fix the problem. I'm not sure that's the correct solution yet.

**Comment by zeromus** [comment]
That wasn't the correct solution, turned out to be something entirely different. Game's sense of whether there were errors was scrambled by other bugs
